### ISSUE TITLE
Bower install doesn't change bower.json

### ISSUE THREAD

**Issue by KevinBurton** [bower/bower#1643] opened 2015-01-04 22:29 UTC
I am on Windows (windows 7) and I execute the following 'bower install jquery --save' and I get the following output:

> bower install jquery --save
> bower resolve       git://github.com/jquery/jquery.git#*
> bower download      https://github.com/jquery/jquery/archive/2.1.3.tar.gz
> bower extract       jquery#\* archive.tar.gz

There are two problems (that are probably manifestations of the same problem)

1) Notice that in the output from bower this is no 'install' step.
2) bower.json does not get updated with the new dependences.

Ideas?

**Comment by sheerun** [comment] 2015-01-04 23:01
Do you use `bower` as package.json dependency? What is your bower version?

Do simple pre- and post-install hooks work?

**Comment by KevinBurton** [comment] 2015-01-05 11:17
I installed bower with npm like: ‘npm install bower –g’. So it was installed ‘globally’ not as a package.json dependency. I am running version 1.3.12. I am not sure how to test pre- and post-install hooks.

Thank you.

**Comment by sheerun** [comment] 2015-01-05 11:19
Here is documentation for hooks: https://github.com/bower/bower/blob/master/HOOKS.md

**Comment by KevinBurton** [comment] 2015-01-05 11:47
The hooks don't seem to work. I have a .bowerrc file that now looks like:
{
  "directory": "public/vendor",
  "scripts": {
        "preinstall": "echo pre",
        "postinstall": "echo post",
        "preuninstall": "echo pre-uninstall"
    }

}

But I don't see any extra messages when I run 'bower install jquery --save'.

**Comment by sheerun** [comment] 2015-01-05 11:49
I don't think echo works because it's built-in command. You need to create executable script, and call it, like "node myprehook.js"

**Comment by KevinBurton** [comment] 2015-01-05 14:18
So what would the myprehook.js look like to mimic the echo?

**Comment by sheerun** [comment] 2015-01-05 15:58
console.log('hello') should be ok

**Comment by mykhael** [comment] 2015-01-05 16:43
@KevinBurton you should use the -s flag when running bower install, this should update the bower.json manifest file with the newly installed package listed

**Comment by KevinBurton** [comment] 2015-01-05 16:49
Isn't --save the same as -s?

**Comment by mykhael** [comment] 2015-01-05 16:54
@KevinBurton Yes, you can use the --save flag and I'd actually recommend that over the -s flag. Head over to issue #1468 and see if this helps as well.

**Comment by mykhael** [comment] 2015-01-05 23:24
@KevinBurton may you close this issue if you have figured things out?

**Comment by KevinBurton** [comment] 2015-01-05 23:52
The hooks don't work. I have the following script (that I call out.js):

function logArrayElements(element, index, array) {
  console.log('a[' + index + '] = ' + element);
}

// Note ellision, there is no member at 2 so it isn't visited
process.argv.forEach(logArrayElements);

The .bowerrc file looks like:
{
  "directory": "public/vendor",
  "scripts": {
       "preinstall" : "node out.js pre %",
       "postinstall" : "node out.js post %",
       "preuninstall" : "node out.js preuninstall %;"
  }
}
The output from bower install jquery --save is only:

bower not-cached    git://github.com/jquery/jquery.git#*
bower resolve       git://github.com/jquery/jquery.git#*
bower download      https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower extract       jquery#* archive.tar.gz

It doesn't seem to make it to the 'Install' phase.

Ideas?

**Comment by sheerun** [comment] 2015-01-05 23:54
I'm out of ideas. I'd need to test this on windows machine. Can someone reproduce this issue?

**Comment by mykhael** [comment] 2015-01-06 00:07
@sheerun we'll I have a backup windows 8.1 machine that I'll test this on, I'll see were it would lead to

**Comment by KevinBurton** [comment] 2015-01-06 01:01
If it matters I am on Windows 7 64 bit Service Pack 1. On a Dell Sudio XPS 435T.

**Comment by mykhael** [comment] 2015-01-06 02:00
@KevinBurton I will test your issue on windows 8.1 tomorrow for yah

**Comment by KevinBurton** [comment] 2015-01-06 02:00
Thank you.

**Comment by mykhael** [comment] 2015-01-06 02:02
@KevinBurton :+1:

**Comment by rijilk** [comment] 2015-01-07 09:49
hii i got this error while trying to install angular-chosen-localytics

bower EISDIR        EISDIR, open '/tmp/george/bower/chosen_v1.3.0-3308-b2v7KE/docsupport/'

Stack trace:
Error: EISDIR, open '/tmp/george/bower/chosen_v1.3.0-3308-b2v7KE/docsupport/'

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/usr/local/lib/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:574:44

can some one help me????????

**Comment by KevinBurton** [comment] 2015-01-07 14:04
Will --verbose give me a stack trace? No error is presented.

**Comment by sheerun** [comment] 2015-01-07 14:05
I was talking rijilk

**Comment by rijilk** [comment] 2015-01-08 05:37
only this is shown there??

**Comment by KevinBurton** [comment] 2015-01-12 00:31
--verbose gives me:

>bower install jquery --verbose
bower not-cached    git://github.com/jquery/jquery.git#*
bower resolve       git://github.com/jquery/jquery.git#*
bower download      https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower extract       jquery#* archive.tar.gz

The process still doesn't seem to reach the install stage.

**Comment by mykhael** [comment] 2015-01-12 01:11
@KevinBurton @sheerun well I've tested this and everything seemed to install okay until I ran the the command with the --verbose flag, I received the same output so this is definitely a focus on windows.

**Comment by sheerun** [comment] 2015-01-12 10:02
I tested it on Windows as well, and `bower.json` is modified correctly. If you use `bower install` second time, the "install" log is missing, but entry is added to `bower.json` anyway. Please prepare failing test.

**Comment by KevinBurton** [comment] 2015-01-12 12:32
In my case bower install query --save neither modifies bower.json or outputs the 'install' notification.

**Comment by KevinBurton** [comment] 2015-01-12 12:33
Query -> jquery

**Comment by KevinBurton** [comment] 2015-01-25 04:33
The issue is marked as "requires feedback". What feedback is needed?

**Comment by sheerun** [comment] 2015-01-25 14:03
Failing test case, because I can't reproduce.

**Comment by KevinBurton** [comment] 2015-02-08 01:52
Any hints on how I could add some debug statements or something to see the cause of the error?

**Comment by KevinBurton** [comment] 2015-02-10 18:17
I am finding that

<user specific>\Roaming\npm\node.exe ./node_modules/bower/bin/bower install jquery --save

works

But 

bower install jquery --save

still does not work. Any ideas what is wrong with my configuration?

**Comment by TonnyORG** [comment] 2015-05-23 22:12
I have the same issue on Ubuntu 15.04, bower install won't update bower.json and also it don't support -S --save option

**Comment by helzgate** [comment] 2015-05-27 19:53
As of 5/27 using the lastest everything from Linuxmint, node, bower, etc.  Anyway, the -s doesn't do anything.  "--save" does work though, like when doing: "bower install --save bootstrap".   One thing I noticed, if I install bootstrap before jquery, it won't pick up jquery when I run "bower init" or if I run "bower install --save bootstrap".  If I install jquery first, then bootstrap, it has no issue picking up both.

**Comment by 121052** [comment] 2015-09-08 19:02
For people having problems with making 'bower install <package name>' update the bower.json file create a new bower.json file by running 'bower init' and simply press enter until done. This did it for me.

**Comment by mad-panda** [comment] 2016-03-01 00:36
Still having the same issue here, running on Cloud9 IDE.

1. create bower.json file with "bower init", press 'enter' through all questions; this successfully creates bower.json

2. manually create .bowerrc file and set, {"directory":"vendor/assets/bower_components"}

3. install packages with "bower install angular angular-ui-router bootstrap --save"

Packages get properly installed in the directory i set in .bowerrc, but dependencies are still not added to bower.json file.
I know i can just add dependencies manually to the bower.json file, then run "bower install", but i'm wondering why above is not working.

**Comment by camohub** [comment] 2016-03-15 21:46
I have the same problem.

**Comment by Freakachoo** [comment] 2016-06-09 13:12
I've found that if execute "bower install --save..." in Git Bash (tested on Windows 10) - bower.json is not updated, but if run it in "cmd" tool - it works.
Also, i've found that when i tried to run "bash init" in git bash - it said "Register requires an interactive shell".
Maybe these issues are related to that.

**Comment by simon-nguyen** [comment] 2016-06-26 10:08
I want to share my experience with the same "bower install **--save** doesn't update bower.json"

I'm using a laptop running Windows 10 x64. I have the lastest bower install globally. My project was generated using yo generator so there's already bower.json and .bowerrc files. At that time I was trying to update all my angular packages because the generated project used "not up-to-date" angular packages, for example angular 1.5.0 (current is 1.5.7)

I ran "bower update --save" to update all my packages (in CMD tool). The update process showed up and said that all the packages was installed successfully. But my bower.json didn't change at all. The file still contained the 1.5.0 version not 1.5.7

I searched and came to this issue post. And noticed one important thing I opened my bower.json file in Visual Studio Code and I could really be sure that the this editor doesn't check for file content changed outside the program.

- backup my current bower.json
- deleted the current bower.json
- ran "bower init"
- answered, chose options while bower.json file was being initialized
- didn't know how bower know and added all the angular 1.5.0 (from previous session) into the brand new initialized bower.json
- ran bower install angular angular-animate... --save (haven't tested with bower update --save yet) and after everything succeeded installed. I select the notepad++ window and the program notified me the change was made. I click Yes to reload the bower.json file content. And every thing (angular packages) was set to the 1.5.7

Hope this help someone.

**Comment by ShriN** [comment] 2016-08-03 15:43
I am on Windows 10 Pro 32 bit with latest VS code. I don't see this issue on install, everything is working as expected.

**Comment by i-try-it** [comment] 2018-04-14 11:37
I have this issue reproduced on win 10

**Comment by sheerun** [comment] 2020-04-26 14:19
This issue got stale, we waven't found a way to reproduce this issue

**Closed by sheerun** 2020-04-26 14:19 UTC
Labels: requires feedback, windows
