### ISSUE TITLE
package resolution issue in 1.5.x

### ISSUE THREAD

**Issue by gazal-k** [bower/bower#1896] opened 2015-08-25 12:07 UTC
When using bower 1.4.1 a package specification: `dcjs#~2.0.0` correctly resolves to `dcjs#2.0.0-beta.17`
But when using bower 1.5.1, getting the following error

```sh
bower dcjs#~2.0.0                              ENORESTARGET No tag found that was able to satisfy ~2.0.0

Additional error details:
Available versions: 2.0.0-beta.17, 2.0.0-beta.16, 2.0.0-beta.15, 2.0.0-beta.14, 2.0.0-beta.13, 2.0.0-beta.12, 2.0.0-beta.11, 2.0.0-beta.10, 2.0.0-beta.9, 2.0.0-beta.8, 2.0.0-beta.7, 2.0.0-beta.6, 2.0.0-beta.5, 2.0.0-beta.4, 2.0.0-beta.3, 2.0.0-beta.2, 2.0.0-beta.1, 2.0.0-alpha.5, 2.0.0-alpha.4, 2.0.0-alpha.3, 2.0.0-alpha.2, 2.0.0-alpha, 1.7.3, 1.7.2, 1.7.1, 1.7.0, 1.6.0, 1.5.0, 1.4.0, 1.3.0, 0.9.1, 0.7.1, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0
```

**Comment by sheerun** [comment] 2015-08-25 20:40
I've reverted semver upgrade in 1.5.2, so it should be fixed now..

**Closed by sheerun** 2015-08-25 20:40 UTC

**Comment by lebolo** [comment] 2015-08-26 19:17
I don't have a particular need for _semver 5.x_, but I do favor newer versions of any dependency in general. So is reverting really the solution here? In #1852, you said

> Makes sense. As I said the benefits overweight drawbacks (backward-incompatibility can only happen if package consists of only prereleases and user required non-prerelease version), so I'm merging it.

I think developers who require _dcjs 2.0.0-beta.x_ should explicitly ask for `dcjs#~2.0.0-beta.x` or move up to a an actual release version.

So I would vote for keeping _semver 5.x_, thoughts?

**Comment by gazal-k** [comment] 2015-08-27 04:30
@lebolo now that I read up on the breaking change in semver 5.x with regard to pre-release tags and the reason for that change, I think I agree.

Just to confirm, if I need the latest beta of dcjs, the bower dependency would have to be: `dcjs#>2.0.0-beta.0` ?

**Comment by donaldpipowitch** [comment] 2015-08-27 05:11
I think so, yes. semver 5.x should be the correct behavior, not a bug.

**Comment by JSteunou** [comment] 2015-08-27 07:31
+1 2.0.0 starts is 2.0.0 stable not beta included

**Comment by sheerun** [comment] 2015-08-27 17:19
I was wrong as this can break things more often: not only when package consists of only pre-releases, but also when selected range (like 2.0.x) consists only of prereleases.

Given large usebase of bower 1.x, stability should be a priority. Personally, I'd like to see some kind of `--beta` flag for bower for opting in for such changes, and then make it default in 2.0.0.

**Comment by zmirc** [comment] 2015-08-28 06:25
@sheerun I agree. +1
