### ISSUE TITLE
TypeError: LRU: key must be a string or number. Almost certainly a bug!

### ISSUE THREAD

**Issue by xzyfer** [bower/bower#2047] opened 2015-11-25 23:53 UTC
This error has returned as of 1.6.6 when running `bower install --allow-root --quiet`.

```
TypeError: LRU: key must be a string or number. Almost certainly a bug! undefined
    at typeCheckKey (/my-app/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:20:19)
    at LRUCache.get (/my-app/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:230:3)
    at /my-app/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
    at _fulfilled (/my-app/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/my-app/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/my-app/node_modules/bower/node_modules/q/q.js:796:13)
    at /my-app/node_modules/bower/node_modules/q/q.js:857:14
    at runSingle (/my-app/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/my-app/node_modules/bower/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:408:9)
```

```
$  node -v
v2.5.0
$  node -p process.versions
{ http_parser: '2.5.0',
  node: '2.5.0',
  v8: '4.2.77.21',
  uv: '1.6.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '44',
  openssl: '1.0.2d' }
$  node -p process.platform
darwin
$  node -p process.arch
x64
```

**Comment by kunyan** [comment] 2015-11-26 08:40
```shell
root@da83d9532a93:/# bower install --allow-root --quiet
root@da83d9532a93:/# node -p process.versions
{ http_parser: '2.5.0',
  node: '2.5.0',
  v8: '4.2.77.21',
  uv: '1.6.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '44',
  openssl: '1.0.2d' }
root@da83d9532a93:/# node -p process.arch
x64
root@da83d9532a93:/# bower -v
root@da83d9532a93:/# bower install jquery --allow-root --quiet
root@da83d9532a93:/# ls
bin  boot  bower.json  bower_components  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```
@xzyfer I can't reproduce it, can you post your bower.json ?

**Comment by Nopzen** [comment] 2015-11-26 09:52
Same error is pressent on node version 0.12.5.

**Comment by daltones** [comment] 2015-11-26 12:06
I'm having the same issue with bower 1.6.6 and node 4.2.2.

In my case seems like the problem occurs if you set a branch name in some dependency version. Like this:

```
"jquery.easy-pie-chart": "master"
```
or
```
"jquery.easy-pie-chart": "rendro/easy-pie-chart#master"
```
or similar.

I also notice that the error occurs just for the first dependency matching this pattern while resolving.

Commit hashes works fine here.

**Comment by Tenzer** [comment] 2015-11-26 12:21
I had the same problem with both Bower 1.6.6 and 1.6.7 on Node 4.2.2 and 5.1.0. Removing the `~/.cache/bower` folder solved the problem for me, for some reason.

**Comment by Nopzen** [comment] 2015-11-26 12:30
I can confirm the fix @Tenzer suggests, on v4.0 but wont fix on v0.12.5.

**Comment by frederikbosch** [comment] 2015-11-26 12:45
I cannot confirm the fix by @Tenzer, I am not bower 1.6.6 and node v4.2.2.

**Comment by kunyan** [comment] 2015-11-26 17:14
#2040 would fix this issue

**Comment by sheerun** [comment] 2015-11-26 17:28
I've merged the fix and I'm going to release soon.

**Closed by sheerun** 2015-11-26 17:28 UTC

**Comment by NextZeus** [comment] 2016-10-09 08:44
bower update

**Comment by frederikbosch** [comment] 2016-10-09 18:04
Thanks, never knew that the command existed.
