### ISSUE TITLE
Bower fails to extract archive from Github

### ISSUE THREAD

**Issue by pronebird** [bower/bower#1980] opened 2015-11-01 09:40 UTC
I am trying to install this thing: https://github.com/tbosch/autofill-event.

`.bowerrc`:

```
{ "directory": "assets/vendor" }
```

I run bower install then...

```
$ bower install autofill-event
bower autofill-event#*      not-cached git://github.com/tbosch/autofill-event.git#*
bower autofill-event#*         resolve git://github.com/tbosch/autofill-event.git#*
bower autofill-event#*        download https://github.com/tbosch/autofill-event/archive/v1.0.0.tar.gz
bower autofill-event#*         extract archive.tar.gz
bower autofill-event#*        resolved git://github.com/tbosch/autofill-event.git#1.0.0
```

Checking directory after installation:

```
$ ls -la assets/vendor/autofill-event 
total 64
drwxr-xr-x  10 pronebird  staff   340 Sep 15 14:44 .
drwxr-xr-x   7 pronebird  staff   238 Nov  1 10:29 ..
-rw-r--r--   1 pronebird  staff   621 Sep 15 14:44 .bower.json
-rw-r--r--   1 pronebird  staff    38 Sep 15 14:44 .bowerrc
-rw-r--r--   1 pronebird  staff    36 Sep 15 14:44 .gitignore
-rw-r--r--   1 pronebird  staff   103 Sep 15 14:44 .gitmodules
-rw-r--r--   1 pronebird  staff  1099 Sep 15 14:44 LICENSE
-rw-r--r--   1 pronebird  staff  2011 Sep 15 14:44 README.md
-rw-r--r--   1 pronebird  staff   276 Sep 15 14:44 bower.json
-rw-r--r--   1 pronebird  staff   522 Sep 15 14:44 package.son
```

This is not what I see in downloaded archive from github.

No source files, nothing extracted, only licenses.

Using bower 1.6.5. Worked before.

**Comment by dakoon2003** [comment] 2015-11-19 22:19
Try running an npm install here and let me know what happens.

**Comment by BenMann** [comment] 2015-12-03 18:20
Works for me with version 1.6.8.
```
Bens-MacBook-Pro:autofill-event Ben$ ls -la  
total 64   
drwxr-xr-x  11 Ben  staff   374  3 Dez 19:17 .   
drwxr-xr-x   3 Ben  staff   102  3 Dez 19:17 ..   
-rw-r--r--   1 Ben  staff   621  3 Dez 19:17 .bower.json   
-rw-r--r--   1 Ben  staff    38 31 Jan  2014 .bowerrc
-rw-r--r--   1 Ben  staff    36 31 Jan  2014 .gitignore
-rw-r--r--   1 Ben  staff   103 31 Jan  2014 .gitmodules
-rw-r--r--   1 Ben  staff  1099 31 Jan  2014 LICENSE
-rw-r--r--   1 Ben  staff  2011 31 Jan  2014 README.md
-rw-r--r--   1 Ben  staff   276 31 Jan  2014 bower.json
-rw-r--r--   1 Ben  staff   522 31 Jan  2014 package.json
drwxr-xr-x   3 Ben  staff   102 31 Jan  2014 src

Bens-MacBook-Pro:autofill-event Ben$ ls -la src
total 8
drwxr-xr-x   3 Ben  staff   102 31 Jan  2014 .
drwxr-xr-x  11 Ben  staff   374  3 Dez 19:17 ..
-rw-r--r--   1 Ben  staff  3037 31 Jan  2014 autofill-event.js
Bens-MacBook-Pro:autofill-event Ben$ 
```

**Comment by Utsav2** [comment] 2015-12-08 19:45
It also worked for me with 1.6.5

**Comment by sheerun** [comment] 2015-12-09 08:51
@bower/windows  Could you test it on Windows with .bowerrc to `{ "directory": "assets/vendor" }`

@pronebird If we won't find a way to reproduce, we'll need to close it.

**Comment by pronebird** [comment] 2015-12-09 08:58
@sheerun I cannot reproduce it anymore either, still on 1.6.5. Must be a fluke.

**Comment by sheerun** [comment] 2015-12-09 09:00
Well, the worst kind of, because for sure it exists but we can't trace it ;/

**Closed by sheerun** 2015-12-09 09:00 UTC
Labels: help wanted

**Comment by TheRakken** [comment] 2015-12-09 09:14
I've tested on windows 7 with bower 1.7.0 and it works ok.
