### ISSUE TITLE
strict-ssl option has no effect in 1.6.5

### ISSUE THREAD

**Issue by Weetbix** [bower/bower#2021] opened 2015-11-18 10:40 UTC
The setting the strict-ssl option to false doesn't seem to have any effect in 1.6.5.

We are routing traffic through a proxy and need this set to false. When set both on the commandline using --config and in the .bowerrc to false we still receive self signed certificate errors and it fails to download packages from github.

Rolling back to 1.5.2 fixed the issue.

**Comment by sheerun** [comment] 2015-11-18 13:01
It's fixed on master, but we need to also fix the tests on 0.10 before releasing patch..

**Comment by faceleg** [comment] 2015-11-18 22:13
FYI the issue is in https://github.com/sheerun/fs-write-stream-atomic/commit/81caa0fad60125bf9a208b77ae3217119a29f474

**Comment by sheerun** [comment] 2015-11-27 19:15
Actually it was fixed in https://github.com/bower/bower/commit/931b0a89057cf43bdd95ff25d134fd9fb26eb0a1 and released in bower 1.6.8

**Closed by sheerun** 2015-11-27 19:15 UTC
Labels: question
