### ISSUE TITLE
Bug in bower where two sub-directories starts with the same string

### ISSUE THREAD

**Issue by lukanus** [bower/bower#1378] opened 2014-06-30 12:54 UTC
I have a ./project/ folder where all my projects are.
Inside it, I had ./Dashboard folder.
After some time I decided to clean up this so I renamed the original ./project/Dashboard into ./project/Dashboard_v1 , and I cloned repository with bower once again as ./project/Dashboard. 

When I run `bower install`, it won't work, and `bower update` in new directory, is trying to change things inside the old folder.

It stopped happening when I change the old folder's name to _Dashboard_v1.
You might have somewhere in the code regexp that is checking only beginning of the path within a loop, so the later one will also pick up.

**Comment by sheerun** [comment] 2015-04-13 22:23
@lukanus I'm closing this because we can't reproduce. If you still experience this issue, please open another ticket with more info how to do it. Thanks anyway for trying to report it :)

**Closed by sheerun** 2015-04-13 22:23 UTC
Labels: requires feedback
