### ISSUE TITLE
v.1.8.0 gives error on install via Git: "ENOTFOUND Package git not found"

### ISSUE THREAD

**Issue by liquid1982** [bower/bower#2392] opened 2016-11-14 20:36 UTC
I'm receiving the following error when I try to install packages via Git (`git@...`).

```sh
vincenzo:~/ $ bower install git@github.com:stevemao/left-pad.git                                                                                                      
bower                        ENOTFOUND Package git not found
```

Everything works fine using `https`:

```sh
vincenzo:~/ $ bower install https://github.com/stevemao/left-pad.git                                                                                                  
bower left-pad#*            not-cached https://github.com/stevemao/left-pad.git#*
bower left-pad#*               resolve https://github.com/stevemao/left-pad.git#*
bower left-pad#*              download https://github.com/stevemao/left-pad/archive/v1.1.3.tar.gz
bower left-pad#*               extract archive.tar.gz
bower left-pad#*              resolved https://github.com/stevemao/left-pad.git#1.1.3
bower left-pad#^1.1.3          install left-pad#1.1.3

left-pad#1.1.3 bower_components/left-pad
```

Something changed in the 1.8.0 version, but I wasn't able to understand if the former version is now deprecated.

**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
2.14.7
v4.2.1
```

**Additional environment details (proxy, private registry, etc.):**

N/A

**Steps to reproduce the issue:**

1. run `bower install git@github.com:stevemao/left-pad.git` on v. 1.8.0
2. PANIC

**Comment by liquid1982** [comment] 2016-11-15 00:02
This issue could be related:

https://github.com/bower/bower/issues/2391

**Comment by bglick** [comment] 2016-11-15 15:40
I can confirm that rolling back to 1.7.9 makes the problem go away

````
[master]:~/dev/vendor_portal: sudo npm install -g bower
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
bower@1.8.0 /usr/lib/node_modules/bower
[master]:~/dev/vendor_portal: bower install git@github.com:Vandegrift/chain_common.git
bower                        ENOTFOUND Package git not found
[master]:~/dev/vendor_portal: sudo npm uninstall -g bower
unbuild bower@1.8.0
[master]:~/dev/vendor_portal: sudo npm install -g bower@1.7.9
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
bower@1.7.9 /usr/lib/node_modules/bower
[master]:~/dev/vendor_portal: bower install git@github.com:Vandegrift/chain_common.git
bower chain_common#*            cached git@github.com:Vandegrift/chain_common.git#1.0.13
bower chain_common#*          validate 1.0.13 against git@github.com:Vandegrift/chain_common.git#*
bower chain_common#*               new version for git@github.com:Vandegrift/chain_common.git#*
bower chain_common#*           resolve git@github.com:Vandegrift/chain_common.git#*
bower chain_common#*          checkout 1.0.14
bower chain_common#*          resolved git@github.com:Vandegrift/chain_common.git#1.0.14
bower chain_common#^1.0.14     install chain_common#1.0.14

chain_common#1.0.14 bower_components/chain_common
├── angular#1.4.14
├── angular-bootstrap#2.2.0
├── angular-mocks#1.4.14
├── angular-moment#1.0.0
├── angular-ui-router#0.3.1
├── bootstrap-css#3.3.6
└── jquery#1.11.3
```

**Comment by boromisp** [comment] 2016-11-16 14:29
Could this be because of #2322, more specifically  https://github.com/bower/bower/pull/2322/commits/1eabaefed6a3b2a9aed2f49939e02187196053c5?
And what about this: https://github.com/bower/bower/commit/dc59913098a392901d440d42f5527406f9bb2eb5?

I'm not familiar with the source, just browsed through the recent commits, so I could be on the wrong track.

**Comment by wookoouk** [comment] 2016-11-22 07:05
I didn't know you could use git@github style URLs on bower, I thought you could only use the short form `bower install username/package` from github. I'll put a patch in.

**Comment by boromisp** [comment] 2016-11-22 08:06
We use this URL style for private git repos with ssh key auth.

**Comment by wookoouk** [comment] 2016-11-22 11:10
I cannot see any tests currently in place for supporting git@github.com:USERNAME/PACKAGE.git style URLS, unless any core devs have an issue with it I will add tests and fixes for them

**Comment by liquid1982** [comment] 2016-11-22 17:13
@wookoouk no worries, it happens :) you can find that URL style in the docs, with other styles as well: https://bower.io/docs/api/#install

**Comment by wookoouk** [comment] 2016-11-22 17:18
My solution to this is to get the last `@` after the last '/' (if any) and only replace that with a '#' instead of replacing all `@`'s. (damm regex)

**Comment by wookoouk** [comment] 2016-11-22 17:26
https://github.com/bower/bower/pull/2395

**Comment by Alber70g** [comment] 2018-02-09 10:19
Related issue occurs with 1.8.2 when installing from a private repo. 

Command: `bower i -S "ssh://git@gitlab.xyz.net:2222/Teamname/reponame.git"`

Error: `ENOTFOUND Package ssh://git not found`

**Comment by bennypowers** [comment] 2018-03-05 13:36
We had this problem with a gitlab private repo, and our solution was to enable access to the deploy key for that private repo. YMMV

**Comment by isolationism** [comment] 2018-03-29 14:29
I was having this problem with Bower 1.8.2 as well. Updating to Bower 1.8.4 resolved the problem.

**Comment by benmann** [comment] 2018-03-31 11:45
Fixed by https://github.com/bower/bower/pull/2395

**Closed by benmann** 2018-03-31 11:45 UTC
