### ISSUE TITLE
bower --save fails to update manifest when ANY install fails

### ISSUE THREAD

**Issue by spinloop** [bower/bower#1652] opened 2015-01-09 18:52 UTC
bower version 1.3.3 
node v0.10.26

--------------------------------

I encountered this behavior was unexpected and is wondering if it is design choice or a true bug.  
steps to reproduce:
`bower install bluebird fakePackageName --save`

bluebird is not saved to bower manifest

I expected bluebird to be written to the manifest file because it installed correctly but I was not notified that there was a failure

I'm not sure if this was a design choice but if it was how would you feel about adding a message to alert the user to the fact that noting was written to the manifest file.

Thank you for making this great tool.  I'm more than willing to implement a solution if it was a design choice.

**Comment by mykhael** [comment] 2015-01-09 20:40
@spinloop Hey man, what operating system are you using and this is also a duplicate of issue #1643

**Comment by spinloop** [comment] 2015-01-09 21:42
@mykhael i'm using OS X Yosemite 10.10.1

sorry about the duplication - i did a quick search through the open issues and didn't see it but obviously missed it

**Comment by mykhael** [comment] 2015-01-10 01:42
@spinloop no man you are fine, I do this all the time but I recommend commenting your problem on issue #1643 so that the bower developers change the tag from `windows` to `bug` because it's happening on more than one os. Also since this is a duplication, I recommend closing this issue.

**Comment by KevinBurton** [comment] 2015-01-12 00:34
So being new to this game I am not sure what I am to do?

>bower install jquery --save
bower not-cached    git://github.com/jquery/jquery.git#*
bower resolve       git://github.com/jquery/jquery.git#*
bower download      https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower extract       jquery#* archive.tar.gz

It doesn't work. Suggestions?

**Comment by sheerun** [comment] 2015-01-12 09:42
Please prepare failing test, and submit it in PR.

**Comment by sheerun** [comment] 2015-01-12 10:06
@spinloop I checked it on Windows, and `bluebird` is not installed in bower components. `bower install` is supposed to be all or nothing, so it seems like correct behavior.

**Comment by KevinBurton** [comment] 2015-01-12 12:27
bower install query --save fails.

**Closed** 2015-09-24 13:13 UTC
Labels: enhancement, requires feedback
