### ISSUE TITLE
Allow bower to finish current downloads on failure

### ISSUE THREAD

**Issue by aldavigdis** [bower/bower#1874] opened 2015-08-06 10:53 UTC
I am currently working on-site with really bad internet connectivity and I'm running into issues where bower simply stops every current download when failing to retrieve a single git repository.

Here's an example:

```
bower bootstrap#>=2.0.4 <4.0            progress received 0.1MB of 3.1MB downloaded, 3%
bower bootstrap#>=2.0.4 <4.0            progress received 0.1MB of 3.1MB downloaded, 3%
bower bootstrap#>=2.0.4 <4.0            progress received 0.1MB of 3.1MB downloaded, 4%
bower angular-ui-router#~0.2.10            EPERM EPERM, unlink 'C:\Users\STEFAN~1\AppData\Local\Temp\STEFANVIGNIR-W7-ste
fanvignir\bower\angular-ui-router-5984-yaI6zB\archive.tar.gz'

Stack trace:
Error: EPERM, unlink 'C:\Users\STEFAN~1\AppData\Local\Temp\STEFANVIGNIR-W7-stefanvignir\bower\angular-ui-router-5984-yaI
6zB\archive.tar.gz'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRender
er.js:82:37)
    at Logger.<anonymous> (c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:45:20
    at _rejected (c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
    at c:\Users\stefanvignir\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.2
OS: Windows_NT 6.1.7601 ia32
```

In that case, bower could have finished downloading Bootstrap and at least validated and cached it before exiting with an error.

**Comment by faceleg** [comment] 2016-03-01 14:10
I've spent the last month in China and agree that this can be painful. Marked as enhancement as it's not a bug.

@bower/contributors to discuss whether this enhancement should be implemented, if so how, by whom, update labels etc.

**Comment by stefanvignir** [comment] 2016-03-23 10:36
Just to follow up on this; it's really painful to show the new and trendy JS stuff to a team of .Net developers and see this failing over and over again due to instabilities in internet connectivity.

**Comment by sheerun** [comment] 2020-04-26 15:18
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)

**Closed by sheerun** 2020-04-26 15:18 UTC
Labels: enhancement
