### ISSUE TITLE
Meet an error when certain project needs certain version of compoment while the denpency with no version target

### ISSUE THREAD

**Issue by thinksource** [bower/bower#852] opened 2013-09-04 15:41 UTC
I work on windows 7
I want use bower install the bootstrap
since the bootstrap depend jquery, I install jquery first.
Follow is my code: 

>git clone git://github.com/twbs/bootstrap.git
>cd bootstrap
>bower install jquery
bower not-cached    git://github.com/components/jquery.git#>= 1.9.0
bower resolve       git://github.com/components/jquery.git#>= 1.9.0
bower not-cached    git://github.com/components/jquery.git#*
bower resolve       git://github.com/components/jquery.git#*
bower ENORESTARGET  No tag found that was able to satisfy >= 1.9.0

Additional error details:
No versions found in git://github.com/components/jquery.git

the jquery seems no version on github, while the bootstrap need jquery>=1.9.0

**Comment by KidA001** [comment] 2015-03-18 03:36
This issue was happening for me and was due to the bower.json bootstrap-sass version being set to 2.3.1 which was not an available release according to bower. I opened my bower.json and changed it to 3.1.0 and it seems to be working now. Hope this might help someone else.

**Comment by wheany** [comment] 2015-03-19 15:52
I had a similar problem with ember#1.10.0
So then I tried `bower install --save ember#1.11.0-beta.5` which worked.
I then retried `bower install --save ember#1.10.0` and it complained:
`Unable to find a suitable version for ember, please choose one:`
`4) ember#1.10.0 which resolved to 1.10.0`
[other lines omitted]

I selected 4 and suddenly it worked. I have no idea why.

**Comment by llbbl** [comment] 2015-06-17 03:47
adding a bower version to the package.json file fixed it for me.... even thou you STILL have to install it globally 

Either this
```
  "dependencies": {
    "bower": "~1.4.1"
  },
```

or This will work

```
  "dependencies": {
    "bower": "~1.4.1"
  },
```

Well actually not totally sure that will fix the error for you all because I was getting it when I ran npm install... so hopefully that fixes it for you and sorry if not.

**Comment by m0n1ker** [comment] 2015-09-20 01:36
I found this thread after I experienced some of the same error messages. I found a solution that could be of interest to some users and thought I'd post it here.

When using ConEmu on Windows (Which is a pretty popular terminal replacement) the default option to "Inject ConEmuHk" causes bower to malfunction. For instance, when I go to install jQuery, it will only recognize the 1.x tags. When I un-check the inject option, it recognizes all of the tags.

I'm not sure whether the problem is with ConEmu's DLL or with bower, but I though I would mention this either way. When running git ls-remote all of the remote tags are listed properly.

Bower: v1.5.2
Git: v2.5.3

**Comment by kvickyk** [comment] 2015-09-21 19:44
m0n1ker thank you for that. It solved my problems. I kept doing everything in ComEmu and kept hitting this issue for the last two weeks.

**Comment by grafikkaos** [comment] 2015-10-02 22:24
oh boy... @m0n1ker , thank you so much for this solution.  I use cmder and after unticking the "Inject ConEmuHk" option, i have been able to install / update my bower packages :+1:

**Comment by sheerun** [comment] 2015-10-15 14:57
Closing as it seems it's not an issue with bower, but ConEmuHk as @m0n1ker said..

**Closed by sheerun** 2015-10-15 14:57 UTC
Labels: windows

**Comment by vabc** [comment] 2015-11-26 21:47
Hello, after a few  hours searching a solution for the same problem I found this blog.
I am just trying to execute the simple bower.json file:

{
  "name": "angular-phonecat",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-phonecat",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "1.4.x",
    "angular-mocks": "1.4.x",
    "jquery": "~2.1.1",
    "bootstrap": "~3.1.1",
    "angular-route": "1.4.x",
    "angular-resource": "1.4.x",
    "angular-animate": "1.4.x"
  }
}


and  always the answer was:

>bower install


bower not-cached    git://github.com/angular/bower-angular.git#*
bower resolve       git://github.com/angular/bower-angular.git#*
bower not-cached    git://github.com/twbs/bootstrap.git#*
bower resolve       git://github.com/twbs/bootstrap.git#*
bower not-cached    git://github.com/angular/bower-angular-mocks.git#*
bower resolve       git://github.com/angular/bower-angular-mocks.git#*
bower not-cached    git://github.com/jquery/jquery.git#*
bower resolve       git://github.com/jquery/jquery.git#*
bower not-cached    git://github.com/angular/bower-angular-route.git#*
bower resolve       git://github.com/angular/bower-angular-route.git#*
bower not-cached    git://github.com/angular/bower-angular-resource.git#*
bower resolve       git://github.com/angular/bower-angular-resource.git#*
bower not-cached    git://github.com/angular/bower-angular-animate.git#*
bower resolve       git://github.com/angular/bower-angular-animate.git#*
bower ENORESTARGET  Tag/branch master does not exist

Finally! 
I put a similar dependencies inside a file package.json  and i executed it with npm.

Then everything worked perfectly!

**Comment by sheerun** [comment] 2015-11-27 16:30
Please look at @grafikkaos comment for solution of this problem
https://github.com/bower/bower/issues/852#issuecomment-145169743
