### ISSUE TITLE
Bower Failure with git:// protocol when behind a proxy server

### ISSUE THREAD

**Issue by pkosenko** [bower/bower#2116] opened 2015-12-23 03:56 UTC
I had this problem before and solved it, but it is BACK with a vengeance in the latest Bower 1.7.1.

Bower fails to download packages when it is behind a proxy.  This used to be solvable by putting a ".git/config" file in the folder with the following:

[url "https://"]
    insteadOf = git://

This no longer works.  I was led to believe when I reported this previously that Bower was planning on fixing the issue.  But it has apparently not only NOT fixed it, but caused the previous workaround also to fail.

```
bower neon-elements#^1.0.0              ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/PolymerElements/neon-elements.git", exit code of #128 fa
tal: unable to connect to github.com: github.com[0: 192.30.252.131]: errno=No error

Additional error details:
Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=No error
user@USER /c/software/react/react-test-sites/polymer1 (master)
```

**Comment by faceleg** [comment] 2016-03-01 14:06
I've spent the last month in China and agree that this can be painful. Marked as enhancement as it's not a bug.

@bower/contributors to discuss whether this enhancement should be implemented, if so how, by whom, update labels etc.

**Comment by sheerun** [comment] 2016-04-07 00:01
it should probably work now. we've also changed all git:// urls to https:// in the registry

**Closed by sheerun** 2016-04-07 00:01 UTC

**Comment by pkosenko** [comment] 2016-04-07 20:41
Thanks.  I updated to Bower 1.7.9 and ran a bower install behind a known proxy WITHOUT having to reconfigure a GIT config file to change the protocol.  I experienced no problems.

I am very happy that you decided to make this upgrade to Bower.
