### ISSUE TITLE
Prevent a dependency from installing if it has some flag.

### ISSUE THREAD

**Issue by basharov** [bower/bower#1706] opened 2015-02-20 16:04 UTC
Is that possible to add a feature that would allow to ignore some dependencies when running install if their version, or name have a prefix?

It could look like this:
```json
{
  "name": "MapEditor",
  "version": "0.0.1",
  "dependencies": {
    "leaflet": "~0.7.3",
    "-leaflet-dev": "0.8.*"
  }
}
```

It means that bower should install leaflet 0.7.3 as usually and ignore leaflet-dev 0.8 because there is a minus in its name as a prefix.

It won't break JSON format and easy to use to include/exclude some dependencies temporarily so that not to have to remember all the used libraries which can be eventually needed.

**Comment by sheerun** [comment] 2015-03-11 05:35
This is probably duplicate of #1394

**Closed by sheerun** 2015-03-11 05:35 UTC
