### ISSUE TITLE
Accept npm's config variables in package.json

### ISSUE THREAD

**Issue by zanona** [bower/bower#1711] opened 2015-02-24 22:59 UTC
It would be really awesome if we could be able to set [NPM's config object](https://docs.npmjs.com/files/package.json#config) for setting bower configurations as well, in addition to env vars and having a `package.json` like:

#### package.json
```json
{
  "name": "my-app",
  "private": true,
  "dependencies": {
    "bower": "^1.3.12"
  },
  "config": {
    "bower_directory": "src/vendor",
    "bower_storage__cache": "~/.bower"
  },
  "scripts": {
    "postinstall": "bower install -p",
    "prestart": "bower install --offline",
    "update": "bower update"
  }
}
```

This would be it really good for development and continuous integration as well, without having to reset these variables for every `bower` command called _(using `bower --config` flag)_. Simply running `npm install` would then inherit all those configurations.

**Comment by sheerun** [comment] 2015-03-11 05:29
Isn't it a duplicate of your own issue? :) #1626

Just a note: You can use `.bowerrc` and `ENV` variables for configuring those variables.

That said, I really like this feature, and it should be as easy to implement as allowing `npm_package_bower_` additionally to `bower_` prefix for `ENV` variables.

Would you mind preparing PR with tests for https://github.com/bower/config ?

**Comment by zanona** [comment] 2015-03-11 10:00
@sheerun thanks for the support. Actually I believe this complements #1626 in a way that would partially resolve one of its issues. I have managed to allow `npm_package_config_bower` as you have mentioned, however I am not quite sure on how to proceed with the tests considering they would need their own npm instance with the `config` attribute defined on package.json https://github.com/zanona/config/commit/b2bbd68fc4db30164cd4556c31686d6e0fd27902

Please let me know if you have an idea on what would be the proper way to link that to the main test thread.

**Comment by sheerun** [comment] 2015-03-11 15:23
Hey. For filesystem tests I think you can use: https://github.com/tschaub/mock-fs I also think it's possible to edit `process.env` directly in node. No? I think any way is good as long as it is tested somehow.

**Comment by zanona** [comment] 2015-03-12 17:45
hey @sheerun let me know if that's ok now. If so, I can then submit a PR. cheers

**Closed** 2015-03-30 08:14 UTC
Labels: enhancement, help wanted
