### ISSUE TITLE
Syntax error .bower.json when dependency is added too in dependenciesDev

### ISSUE THREAD

**Issue by Maks3w** [bower/bower#1780] opened 2015-04-20 08:44 UTC
Given a package required in `dependencies` and `devDependencies` the file `.bower.json` has append invalid string at the end of the JSON

My use case is to restrict the jQuery version for run unit tests with PhantomJS. 

```json
{
  "dependencies": {
    "package_with_any_jquery_dependency_version": "*"
  },
  "devDependencies": {
    "jquery": "<2.0.0"
  }
}
```

The result `jquery/.bower.json` has this structure

```json
{
  "name": "jquery",
  "version": "1.11.1",
  "main": "dist/jquery.js",
  "license": "MIT",
  "ignore": [
    "**/.*",
    "build",
    "speed",
    "test",
    "*.md",
    "AUTHORS.txt",
    "Gruntfile.js",
    "package.json"
  ],
  "devDependencies": {
    "sizzle": "1.10.19",
    "requirejs": "2.1.10",
    "qunit": "1.14.0",
    "sinon": "1.8.1"
  },
  "keywords": [
    "jquery",
    "javascript",
    "library"
  ],
  "homepage": "https://github.com/jquery/jquery",
  "_release": "1.11.1",
  "_resolution": {
    "type": "version",
    "tag": "1.11.1",
    "commit": "0d5ec2d8ac94a419ee47a39319c43ff9a7326b50"
  },
  "_source": "git://github.com/jquery/jquery.git",
  "_target": "1.11.1"
} "<2.0.0"
}
```

For remark this is the issue:
```json
{
} "<2.0.0"
}
```

Tested on >=1.3.9 up to 1.4.1

**Comment by BenMann** [comment] 2016-03-01 16:45
It is fairly safe to say that this is actually the same issue as https://github.com/bower/bower/issues/2067.
The issue is with one packages resolving `jquery` and some other package `jQuery`.
I'll close in favor of the newer (more elaborate) issue.

**Closed by BenMann** 2016-03-01 16:45 UTC
