### ISSUE TITLE
Nested relative local path bower components cannot resolve path

### ISSUE THREAD

**Issue by leevigraham** [bower/bower#1513] opened 2014-09-10 00:52 UTC
I'm developing multiple private bower components locally and have nested dependencies.

My Project bower.json:

``` json
{
    "name": "nsm-club-evo-app",
    "dependencies": {
        "nsm-form-bundle": "./src/web/bundles/nsmform"
    },
} 
```

requires the `nsm-form-bundle`:

``` json
{
    "name": "nsm-form-bundle",
    "dependencies": {
        "jquery-nsm-collection": "./widgets/collection"
    }
}
```

which requires a local widget:

``` json
{
    "name": "jquery-nsm-collection",
    "main": "src/jquery.nsm.collection.js",
    "dependencies": {
        "jquery-ui": "~1.11.0",
        "velocity": "~0.8.0"
    }
}
```

I'm using this setup to manage dependencies like 'velocity' using `grunt-wiredep`.

**The issue** is that `nsm-form-bundle` has a relative dependency on `jquery-nsm-collection`. When resolving the relative path the path is calculated from the `bower install` root not `./src/web/bundles/nsmform`.

Is there anyway to set a new relative path base path? I've tried adding a `.bowerc` file to the `nsm-form-bundle` and setting the `cwd` property but that had no affect.

**Comment by tomasAlabes** [comment] 2015-02-21 06:38
Any update on this? @leevigraham 
Thanks.

**Comment by leevigraham** [comment] 2015-02-23 05:57
@tomasAlabes I gave it a crack but was a bit out of my depth and now I'm smashed at work :(

**Comment by sheerun** [comment] 2016-05-30 09:18
@leevigraham @pennyfx Evan prepared test suite for your issue, but the issues seem gone: https://github.com/bower/bower/pull/2297

Could you check if the issue is still happening and fix the failing tests so we can reproduce?

**Comment by leevigraham** [comment] 2016-05-30 23:21
@sheerun I'll try to fire up the old project and provide feedback.

**Comment by skyl** [comment] 2016-07-02 02:51
I was doing a relative filesystem dependency. I found that bower does not install that dependency's dependencies. I'm a few versions back from even stable though. So, I will upgrade and see what happens, edit with details.

**Comment by rodrigocnascimento** [comment] 2017-05-03 19:04
I'm also having the same problem. I have two libs http-error-handler and app-service, as it follows:
``` 
"name": "app-service",
"main": "index.js",
"dependencies": {
  "angular": "^1.6.4",
  "httperrorhandler": "../httperrorhandler/"
},
```
And in my main project
```
"app-service": "../libs/app-service/"

Error:
"id": "ENOENT",
"level": "error",
"message": "ENOENT: no such file or directory, stat '/home/Project/httperrorhandler'",
"stacktrace": "Error: ENOENT: no such file or directory, stat '/home/Project/httperrorhandler'"

npm --version 4.2.0
node --version v7.9.0
bower --version 1.8.0
Linux PE02803B 4.4.63-1-MANJARO #1 SMP PREEMPT Fri Apr 21 08:43:38 UTC 2017 x86_64 GNU/Linux
```

**Comment by evanjbowling** [comment] 2017-05-04 00:26
Hi @rodrigocnascimento, from the error message it appears that the relative paths aren't correct. Is this an open-source project you can point me to? If not, can you paste a layout for your project including the location of the bower.json and the "httperrorhandler" project? Using the tree command you can get output like below:

```
.
├── bower-app
│   └── bower.json
└── httperrorhandler

2 directories, 1 file
```

**Comment by rodrigocnascimento** [comment] 2017-05-04 02:46
What I'm trying to do basically is create a service that can be reused over my project, and my httperrorhandler, is a factory that handle my http requests. I'm not with the code right now, but my project has the same structure. For now, I just created two separated modules and installed them. I've noticed the wrong path to the lib1 as it shows on the error message, but how can I manage this?

Thanks :D  

```
[23:20] ~/Projects/raven/libs
[23:20] ~/Projects/raven/web

[23:20] ~/Projects/raven/libs/
├── lib1
│   └── bower_components
│       └── angular
└── lib2
    └── bower_components
        ├── angular
        └── lib1

- lib1/bower.json
{
  "name": "lib1",
  "main": "index.js",
  "dependencies": {
    "angular": "^1.6.4"
  }
}

- lib2/bower.json
{
  "name": "lib2",
  "main": "index.js",
  "dependencies": {
    "angular": "^1.6.4",
    "lib1": "../lib1/"
  }
}
- web/bower.json
{
  "name": "web",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.4.0"
    "lib2": "../libs/lib2/"
  },
  "appPath": "app",
  "moduleName": "webApp"
}

[23:19] ~/Projects/raven/web
  $ bower install --save ../libs/lib2/
bower lib2#*                      copy /user/Projects/raven/libs/lib2
bower lib2#*                  resolved /user/Projects/raven/libs/lib2
bower lib1#*                    ENOENT ENOENT: no such file or directory, stat '/user/Projects/raven/lib1'

Stack trace:
Error: ENOENT: no such file or directory, stat '/user/Projects/raven/lib1'

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 7.2.1
OS: Darwin 15.6.0 x64
```

**Comment by rodrigocnascimento** [comment] 2017-05-04 11:26
I've made some changes and now I'm using my absolute path and it's working fine. But it's the best approach? Sorry for my "false" alarm. And thank you for your time. @evanjbowling

**Comment by justin-c-rounds** [comment] 2017-10-17 18:40
Is there a workaround for this that does not use absolute paths?

**Comment by sheerun** [comment] 2020-04-26 15:32
Unfortunately Bower is deprecated and we won't be fixing this behavior

**Closed by sheerun** 2020-04-26 15:32 UTC
Labels: bug, requires feedback
