### ISSUE TITLE
running 'bower save <package> --save' doesn't respect the resolutions spec

### ISSUE THREAD

**Issue by mgenev** [bower/bower#1669] opened 2015-01-19 21:17 UTC
I have the resolution specified, but when I run to install a particular package, it still fails to resolve. When I add the new package to the json manually and run 'bower install' it does resolve as specified...

**Comment by sheerun** [comment] 2015-03-11 06:05
It's duplicate of #1362

**Closed by sheerun** 2015-03-11 06:05 UTC
