### ISSUE TITLE
insight-bower.yml with EACCESS error by default

### ISSUE THREAD

**Issue by ulpian** [bower/bower#1607] opened 2014-11-24 05:04 UTC
Hey, weird error, I was just doing a fresh install on a server and bower installed fine however when trying to run "bower install" it gave me the EACCESS permission denied error for the ".config/configstore/insight-bower.yml" file.

I never installed bower or npm for that matter via root, this was the first time on this machine that "bower install" was running. When trying to chown the "insight-bower.yml" file it told me it didnt exist, which is true. I resolved it by chown the whole .config folder.

This is with bower v1.3.12. Maybe this is some real bug for bower or just some weird config error on the machine but thought I might flag it up, keep up the good work :)

**Comment by sheerun** [comment] 2015-01-05 00:00
Maybe your `HOME` wasn't set properly? Can you give a way to reproduce?

**Comment by ad3002** [comment] 2015-01-06 13:56
I got similar error today with new installation on Ubuntu with sudo npm install bower -g command, expected config folder was not created in bower installation

```
Error: EACCES, permission denied '/home/username/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:432:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:286:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by ad3002** [comment] 2015-01-06 14:03
Before I've installed mc and it creates .config folder by root so bower simply doesn't have access to it. Fixed with chown.

**Comment by deepakkaithwas** [comment] 2015-01-07 09:32
I just fixed it in Windows.
I have done three things, which one have fixed it I am not sure.
1. Run cmd prompt as administrator.
2. takeown /? this command is equivalent to chown (linux) but for windows.
3. cacls -cacls <file or directory> /E /T /G <user>:F
4. simply go in $USER /Users/calvin/.config/configstore/ and make files unhidden.

it worked for me like charm.
I have been trying to fix this since many days.

**Comment by VictorBargains** [comment] 2015-02-11 23:55
I just got a similar issue trying a first time deployment to openshift. pushed repo, ran npm install, then ran bower install. I am guessing this is because root is the owner of the home directory I get dropped in by the `rhc ssh` command which connects me to the openshift shell. It's trying to mkdirSync ~/.config. Is there a way around this without being able to chown?

---
> bower install

Error: EACCES, permission denied '/var/lib/openshift/54db291bfcf933fd3e000039/.config'
    at Object.fs.mkdirSync (fs.js:642:18)
    at sync (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/node_modules/mkdirp/index.js:70:13)
    at Function.sync (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/node_modules/mkdirp/index.js:76:24)
    at Object.create.all.get (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/var/lib/openshift/54db291bfcf933fd3e000039/app-root/runtime/repo/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
---

**Comment by benhalverson** [comment] 2015-04-08 22:03
I reinstalled my node setup using this git repo https://github.com/brock/node-reinstall 
I was able to install bower -g without sudo. When I run this bash script I am also getting this error. 

Error: EACCES, permission denied '/Users/benhalverson/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/Users/benhalverson/.nvm/v0.10.38/lib/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/Users/benhalverson/.nvm/v0.10.38/lib/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/Users/benhalverson/.nvm/v0.10.38/lib/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/Users/benhalverson/.nvm/v0.10.38/lib/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/Users/benhalverson/.nvm/v0.10.38/lib/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
https://github.com/chyld/apollo/blob/master/setup.sh

**Comment by skolsuper** [comment] 2015-05-10 17:05
I am also having this problem.  Ubuntu 14.04, almost fresh VPS, cannot get bower to do anything at all.  Even `bower cache clean` throws the same error.  Also, I tried deleting bower-github.yml, and now I can't get it back again even after reinstalling bower and then npm+bower.

**Comment by Angel-Gonzalez** [comment] 2015-05-10 18:14
I had the same error on Elementary Os Freya. I fix it changing ownner in both .config and .cache directories with this command <code> sudo chown -R [user name] ~/.config</code> and <code> sudo chown -R [user name] ~/.cache</code> hope works for others

**Comment by skolsuper** [comment] 2015-05-11 02:46
Thanks Angel-Gonzalez, that worked for me too.

**Comment by chasevida** [comment] 2015-05-14 02:29
@Angel-Gonzalez this resolved it for me too - thanks!

**Comment by gougou9903** [comment] 2015-05-19 23:56
@Angel-Gonzalez  this helped me a lot! Thanks!

**Comment by jasonmenayan** [comment] 2015-05-20 21:09
Thank you, @Angel-Gonzalez ! worked for me, too. You're a lifesaver.

**Comment by adrianortuzar** [comment] 2015-05-22 08:53
@Angel-Gonzalez this works in a mac too, thank you.

**Comment by martinmoserswiss** [comment] 2015-05-25 13:13
@Angel-Gonzalez :+1:

**Comment by felixhao28** [comment] 2015-05-26 03:52
TY @Angel-Gonzalez 

I think this should be written somewhere official.

**Comment by kymdusting** [comment] 2015-05-28 11:31
@Angel-Gonzalez ta, nice one.

**Comment by notbrain** [comment] 2015-06-01 20:46
This is still an issue, but I found it via a post install step on StriderCD. After installing node via global nvm, same issues on .config and .cache, they aren't even able to be created. Having to manually change permissions on directories that don't exist once the npm install exits non-zero is not ideal. Is there a better way to get around this?

http://stackoverflow.com/questions/30582124/stridercd-global-post-install-fails-on-bower-access-to-home-config-home-cach

**Comment by pravchuk** [comment] 2015-06-18 23:29
Thanks Angel-Gonzalez, It worked.

**Comment by sudheer594** [comment] 2015-06-22 16:09
Thanks Angel-Gonzalez, that worked for me too.

**Comment by pawat-chom** [comment] 2015-06-23 06:24
@Angel-Gonzalez this resolved it for me too - thanks!

**Comment by alopezo** [comment] 2015-06-30 20:15
@Angel-Gonzalez thanks, that was the solution...

**Comment by lostclawz** [comment] 2015-07-02 20:53
Yes! Thank you @Angel-Gonzalez

**Comment by puny-d** [comment] 2015-07-05 03:39
@Angel-Gonzalez, thanks, help me a lot

**Comment by cliffordfajardo** [comment] 2015-07-09 06:23
Thank you @Angel-Gonzalez

**Comment by XXShen** [comment] 2015-07-14 01:51
@Angel-Gonzalez ,thanks! It works! ha～ha～ha～

**Comment by Muthamizhan** [comment] 2015-07-15 08:54
@Angel-Gonzalez Thanks for your valuable answer :100:

**Comment by EugeneLugin** [comment] 2015-07-17 13:40
@Angel-Gonzalez Thanks a lot! It works!

**Comment by losada24** [comment] 2015-07-22 22:14
@Angel-Gonzalez it worked for me too. Thanks a lot

**Comment by alexclemensua** [comment] 2015-07-29 06:51
@Angel-Gonzalez solution didn't work for me, but this did:
chmod g+rwx ~/.config/configstore

**Comment by vijayperlakota** [comment] 2015-07-30 13:02
@Angel-Gonzalez it worked for me too. Thanks a lot

**Comment by scknechaev** [comment] 2015-08-05 14:30
Guys is you have problem with EACCESS, bower have no permissions to make such operations like removing, adding, rewriting (and other) with files. I fixed it just run this command
sudo bower install --allow-root

**Comment by x3DevGit** [comment] 2015-08-09 14:43
@Angel-Gonzalez  thanks !

**Comment by meni45** [comment] 2015-08-09 21:04
@Angel-Gonzalez Thanks!

**Comment by drigoteixeira** [comment] 2015-10-21 20:12
@Angel-Gonzalez, Your tip was really helpful! Thank you!

**Comment by tim545** [comment] 2015-10-28 22:56
@Angel-Gonzalez solved! Thanks! I was lost on that one

**Comment by bsienn** [comment] 2015-10-31 22:13
seriously this was annoying. Thanks @Angel-Gonzalez 
please fix this already

**Comment by lmorenojr** [comment] 2015-11-01 02:39
@Angel-Gonzalez thanks that resolved it, appreciate it

**Comment by iamryandrake** [comment] 2015-11-03 03:05
Thanks @Angel-Gonzalez Worked for me too!

**Comment by thomasrstegelmann** [comment] 2015-11-10 17:07
@Angel-Gonzalez Thanks a lot!

**Comment by bilalcorbacioglu** [comment] 2015-11-19 08:22
@Angel-Gonzalez Thanks !

**Comment by tonillo** [comment] 2015-11-20 20:59
@Angel-Gonzalez  Thanks works on oxs snow too!

**Comment by J-Weeks** [comment] 2015-11-21 17:10
@Angel-Gonzalez Thanks worked Yosemite.

**Comment by faceleg** [comment] 2015-11-22 19:42
Locking to prevent any more "me too" messages cluttering up the volunteer's review queue.

**Closed by faceleg** 2015-11-22 19:42 UTC
Labels: requires feedback
