### ISSUE TITLE
bower ENOINT        Register requires an interactive shell

### ISSUE THREAD

**Issue by williamquan** [bower/bower#2347] opened 2016-08-22 11:56 UTC
Going over Angular tutorial phonecat, not able to setup bower through directory

get following error message: bower ENOINT        Register requires an interactive shell

tried bower uninstall, bower install, bower init and same message

**Comment by BenMann** [comment] 2016-09-01 11:16
@williamquan Can you try a different terminal? Have you seen those: https://github.com/bower/bower/issues/2080 / https://github.com/bower/bower/issues/802

**Comment by leandroruel** [comment] 2016-09-20 12:09
after read your tip, tried with powershell, and that works

**Comment by BenMann** [comment] 2016-09-20 12:13
I'm closing for now, cause no reponse..

The issue is about using an interactive shell. There are also plenty of issues like this that are already closed. Try searching those or stackoverflow if you need further help. However feel free to comment here again if needed!

**Closed by BenMann** 2016-09-20 12:13 UTC

**Comment by HorchataHTML** [comment] 2017-08-16 09:35
The solution is very easy, work that part with (for example) "Node.js command prompt" and you will not get any errors.

**Comment by AManojKiran** [comment] 2018-10-24 23:22
You Better use your command prompt  don't to the CLI support app Such as git,power shell etc
