### ISSUE TITLE
Implement version constrain system

### ISSUE THREAD

**Issue by IgorMinar** [bower/bower#578] opened 2013-07-01 21:48 UTC
One of really good things that Dart has done is their Pub package manager.

Dart similarly to JavaScript needs to deal with version conflicts in application that have transient dependencies on the same package but various versions of this package.

Their solution is version constrain system that is described in great details at: http://pub.dartlang.org/doc/versioning.html

**Comment by dgreensp** [comment] 2015-04-22 17:58
If you need a fast general-purpose constraint solver in JS, here's Meteor's package that it uses for that purpose: https://github.com/meteor/meteor/tree/devel/packages/logic-solver

I'm the author and maintainer, and happy to answer any questions.  It's basically a nice API wrapping a SAT solver.

**Comment by sheerun** [comment] 2015-04-22 19:49
@dgreensp Hey! For bower we would need solver for Dynamic CSP. That's because bower generally don't have access to all `bower.json` manifests of all package versions. So two questions:

1. Can you add variables during solving?
2. Can you introduce new constraints during solving?
3. Can you add weights for constraints?
4. Does it support cycles?

**Comment by dgreensp** [comment] 2015-04-22 20:33
You can add new variables and constraints at any time and re-solve.  Constraints can be in the form of inequalities over integers, including weighted sums of boolean variables, and you can also optimize integer cost functions.

You can't remove constraints (relax the problem), but you can solve with temporary assumptions, so you can achieve something similar to removing constraints by "guarding" any constraints you don't want to commit to yet behind an assumption variable.  Similarly, to prefer one kind of solution over another, you can first check to see if the better kind of solution is possible, and if it is, require that kind of solution going forward.  To report conflicts, we first guard all the hard constraints behind variables, and then we maximize the number of constraints in force.  If all constraints can be enforced, we proceed; otherwise, we report one minimum set of constraints that would have to be relaxed (which is generally what the user needs to see).

Meteor's version solver (implemented on top of logic-solver) effectively optimizes a cost function that is a vector of integers, where the lexically smallest vector is preferred.  Towards the front of the vector are cost functions like "total number of versions behind, among packages the user has asked us to upgrade", while towards the end are cost functions like "total number of packages chosen", while hard constraints are always enforced, such as the version ranges allowed for each dependency of each version of each package.

We have all the metadata we need in a local sqlite database, and the resulting logic problem can be large, but the whole thing takes under a second.  I don't know Bower very well, so it could be that you need something where the set of constraints is more malleable.  For example, if every package version manifest needs to be read individually by going over the network, and then you need to relax the problem a tiny bit to allow that version and re-solve, logic-solver won't drive that loop.  It could still be a good primitive, though, because you can give it constraints and then query whether the problem is satisfiable or not under additional constraints, or whether a certain cost function value is achievable, etc.

**Comment by sheerun** [comment] 2015-04-23 15:57
I really like the idea of choosing lexically smallest vector of cost functions values!

- Yup, we don't need relaxing as long as we can backtrack somehow.
- Inequalities over integers are pretty useless with Bower uses [semver](https://github.com/npm/node-semver) that has quite complicated semantics. How would you handle it?

Could you extract this SAT solver to npm package? We could build semver solver on top of it :)

**Comment by dgreensp** [comment] 2015-04-23 16:58
Hi @sheerun,

We use semver too.  Here is what we do.  Each package version (like `foo 1.0.0`) has a boolean variable that represents whether it is part of the solution.  For inequalities/ranges, we just list all the legal versions when we generate the solver-level constraint.  For cost functions, we look at how many versions old each part of the semver version is.  So for example, if there were just versions `1.0.0` and `3.0.0` for a package, `3.0.0` would have a "major oldness" of 0, and `1.0.0` would have a "major oldness" of 1.  If, in addition, there were a version `1.0.1`, it would have a "patch oldness" of 0, while `1.0.0` would have a "patch oldness" of 1.  In addition to being convenient, this scheme avoids assigning any special weight in the (unlikely) case that a package author skipped to some high version number.

I will make an npm package.

**Comment by dgreensp** [comment] 2015-04-25 04:15
Just to give you a timeframe, I'm leaving on vacation for a few days, so it might be late next week that I get the package up.

**Comment by dgreensp** [comment] 2015-05-06 23:53
Behold, the logic-solver npm package!

https://www.npmjs.com/package/logic-solver

**Comment by sheerun** [comment] 2020-04-26 13:54
As Bower is not developed anymore, I'm going to close this issue. The solution for this issue is to migrate to yarn with https://github.com/sheerun/bower-away and then use its selective dependency resolution feature: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Closed by sheerun** 2020-04-26 13:54 UTC
Labels: feature
