### ISSUE TITLE
https://bower.herokuapp.com/ seems down!

### ISSUE THREAD

**Issue by kermit6000** [bower/bower#2485] opened 2017-10-11 12:53 UTC
Every bower package cannot be fetched as of today.
`bower what-input#~4.0.3        EINVRES Request to https://bower.herokuapp.com/packages/what-input failed with 410`

http://www.websitedown.info/bower.herokuapp.com

I assume the heroku application needs to be restarted.

**Comment by sheerun** [comment] 2017-10-11 12:54
Duplicate of #2484

**Closed by sheerun** 2017-10-11 12:54 UTC
