### ISSUE TITLE
bower install Error: Cannot find module 'internal/util/types' in Macos

### ISSUE THREAD

**Issue by abkrim** [bower/bower#2497] opened 2017-11-18 09:05 UTC
**Output of `bower -v && npm -v && node -v`:**

```
module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

**Additional environment details (proxy, private registry, etc.):**
npm -v && node -v
5.5.1
v8.9.

**Steps to reproduce the issue:**

1. npm install -g bower
```
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
/Users/abkrim/.nvm/versions/node/v8.9.1/bin/bower -> /Users/abkrim/.nvm/versions/node/v8.9.1/lib/node_modules/bower/bin/bower
+ bower@1.8.2
```
updated 1 package in 7.587s      
2. My package say me run bower install
```
bower install                
module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)    
```

**Additional information:**
Run in macOs HighSierra
Project for Laravel 5.5 and Vue

**Comment by Perturbatio** [comment] 2017-11-19 03:07
Try `npm cache verify` then run bower

**Comment by DaniG2k** [comment] 2017-12-05 06:25
Seeing the same error here.

```
=> bower -v && npm -v && node -v
1.8.2
5.5.1
v8.9.1
```

then

```
npm install bower -g
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
/Users/me/.nvm/versions/node/v8.9.1/bin/bower -> /Users/me/.nvm/versions/node/v8.9.1/lib/node_modules/bower/bin/bower
+ bower@1.8.2
updated 1 package in 5.739s
```

and finally

```
bundle exec rake bower:install
bower.js files generated
/Users/me/Documents/project/app/node_modules/.bin/bower install -p
module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/Users/me/Documents/project/app/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
rake aborted!
Command failed with status (1): [/Users/me/Documents/project/app...]
```

**Comment by liorch88** [comment] 2017-12-24 08:23
Same happened for me. Turned out that I had two different bower versions installed: a new one under nvm, and an old one under "/usr/local/lib/node_modules/bower". I deleted the old one so it would use the new version. That seemed to do the trick.

**Comment by iegik** [comment] 2018-01-11 12:03
duplicate of https://github.com/bower/bower/issues/2393 ?

**Comment by iegik** [comment] 2018-01-11 12:46
Fixed in v1.8.2

**Comment by lparvinsmith** [comment] 2018-01-16 20:34
I just had the same issue -- I fixed it with by using an earlier version of node to run bower commands.

1) `nvm use 6.9` (node 7.0 didn't work)
2) `bower install`
3) go back to your current version of node

**Comment by Andruschenko** [comment] 2018-02-14 16:30
I got the error because in my case bower was not installed.. 🙈

**Comment by AndreaOliveira** [comment] 2018-03-14 21:34
I have the same problem...

**Comment by swapbuk** [comment] 2018-04-04 06:52
I am also facing same problem even after installing bower.

**Comment by punkratz312** [comment] 2018-05-07 09:34
+1

**Comment by bichotll** [comment] 2018-06-10 13:20
`rm -rf /usr/local/lib/node_modules/*` solved the issue for me as @liorcode mentioned above.
It may have happened because of nvm?

**Comment by liorcode** [comment] 2018-06-11 11:27
@bichotll, it is not specifically an NVM issue. It can happen for a lot of reasons. Mine was having more than one global "node_modules" directory. 
When I switched to NVM I did not clean up the previous node_modules location - `/usr/local/lib/node_modules` and it had some old bower leftovers which I was not aware of.
So when I ran "bower install" it actually used this old/broken setup.
You can verify where the bower you are using by running `which bower` (in linux). If you are using nvm, it should be under your '.nvm' folder.

**Comment by sheerun** [comment] 2018-09-28 13:55
As everyone noticed, there are different reasons of such behavior but they have to do with your node environment being in wrong state. Just uninstall all node versions or nvm version you have, remove all node_modules from /usr/local/bin and wherever you find them, and re-install node again, preferably in single location. Each time you change node you need to possibly re-install bower as well.

**Closed by sheerun** 2018-09-28 13:55 UTC
