### ISSUE TITLE
bower list gives "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by charlie9002** [bower/bower#1582] opened 2014-10-31 23:20 UTC
Version 1.3.12 on Win 8.1 with node 0.10.33

I was getting error with bower, so completely uninstalled nodejs and deleted npm directories to get a simple case to show it.

Reinstalled node
Open command prompt in clean directory, ran "npm -g install bower"
Then "bower list", gives this error.

    bower error         Maximum call stack size exceeded
    
    Stack trace:
    N/A
    
    Console trace:
    Trace
        at StandardRenderer.error (C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:17)
        at Logger.<anonymous> (C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
        at Logger.emit (events.js:95:17)
        at Logger.emit (C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
        at C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:20
        at _rejected (C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:797:24)
        at C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:823:30
        at Promise.when (C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1035:31)
        at Promise.promise.promiseDispatch (C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:741:41)
        at C:\Users\cdm\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:509:49
    
    System info:
    Bower version: 1.3.12
    Node version: 0.10.33
    OS: Windows_NT 6.2.9200 x64

I tried installing into a brand new Win 8.1 VM, and it all works ok, so obviously something else on my machine that's interfering or that I've not cleaned up.

Does anyone have an ideas or any suggestions about where to start diagnosing this?

**Comment by sheerun** [comment] 2015-01-05 00:34
Closing because of no feedback. Please post your `bower.json` and steps to reproduce.

You can use StackOverflow for support questions.

**Closed by sheerun** 2015-01-05 00:34 UTC

**Comment by cdmackie** [comment] 2015-03-27 02:02
For anyone else who comes across this. The problem was that XDG_CACHE_HOME was set to an invalid path in Windows environment variables. This causes an infinite loop inside bower-registry-client::initCache where it is trying to create a directory with mkdirp.

I have no idea what set XDG_CACHE_HOME in the first place. Cgywin perhaps?
