### ISSUE TITLE
EACCES: permission denied .config/configstore/bower-github.json

### ISSUE THREAD

**Issue by alexlaw17** [bower/bower#2262] opened 2016-04-20 16:20 UTC
I keep running into this problem. I uninstalled and reinstalled bower. Nothing is working. 

`alexlaw$ bower
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/alexlaw/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)`

**Comment by BenMann** [comment] 2016-04-20 17:36
Did you see this issue: https://github.com/bower/bower/issues/2260
Does it work for you too?

**Comment by alexlaw17** [comment] 2016-04-20 19:29
I'm still getting the same error, even after
`sudo bower install --allow-root`
`sudo bower install <package>`

**Comment by alexlaw17** [comment] 2016-04-20 20:51
fixed it with 
`sudo chown -R $USER:$GROUP ~/.npm`
`sudo chown -R $USER:$GROUP ~/.config`

**Comment by BenMann** [comment] 2016-04-21 06:25
Strange but still a problem with permissions (as also indicated by the error).
Closing for now.

**Closed by BenMann** 2016-04-21 06:25 UTC

**Comment by steveandrewwong** [comment] 2016-05-01 04:15
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

works for me

**Comment by jcanales** [comment] 2016-05-23 17:53
Worked for me as well 

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by beormalte** [comment] 2016-05-24 14:38
Worked for me :)

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by dpanfili** [comment] 2016-05-25 02:36
This helped me - thanks!

**Comment by Samuel7l** [comment] 2016-06-07 23:09
Worked for me :)

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by jkoksharova** [comment] 2016-06-08 13:18
Worked for me too.

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by rswetabh** [comment] 2016-06-08 16:20
Worked for me too.

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by AsherPeruscini** [comment] 2016-06-09 05:02
and me

`sudo chown -R $USER:$GROUP ~/.npm`
`sudo chown -R $USER:$GROUP ~/.config`

**Comment by Shakogun** [comment] 2016-06-09 14:36
Same goes for me

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Pravin-Parkhi** [comment] 2016-06-09 19:15
Worked for me as well

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by pankajdaffodil** [comment] 2016-06-12 13:45
Thanks to all
worked for me .

**Comment by revanthreddya** [comment] 2016-06-14 03:06
Perfect .. thanks @alexlaw17
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by BlackRussian** [comment] 2016-06-21 16:36
Thanks to all
worked for me .

**Comment by emotilla** [comment] 2016-06-22 20:07
### in Ubuntu 14 LTS / DigitalOcean:

sudo chown -R $USER:$GROUP /usr/share/nginx/html/

checkout a good tutorial: 
https://www.digitalocean.com/community/tutorials/how-to-manage-front-end-javascript-and-css-dependencies-with-bower-on-ubuntu-14-04

**Comment by sashacarvajal94** [comment] 2016-06-24 23:05
Great!!! Been with this issue for days! Worked for me too!

**Comment by ragalindoh** [comment] 2016-06-28 20:18
Worked for me, thank you @alexlaw17 

```
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
```

**Comment by dannymac7** [comment] 2016-07-01 22:10
Worked for me, thanks!!!

**Comment by jorgeants** [comment] 2016-07-03 20:11
Worked for me too. Thanks @alexlaw17. :)

**Comment by ils-anshub** [comment] 2016-07-07 11:13
Worked for me as well...Thanks @alexlaw17

**Comment by appssunset** [comment] 2016-07-07 12:52
Worked for me as well

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

But I needed to execute the follow too:
sudo chown -R $USER:$GROUP ~/.cache

**Comment by cliftonc0613** [comment] 2016-07-09 17:31
Worked for me as well

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by NikolaVujanic** [comment] 2016-07-11 11:07
Worked for me :)

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by alansutherland** [comment] 2016-07-16 03:12
Thanks @alexlaw17

**Comment by richardj** [comment] 2016-07-19 10:40
worked for me as well! :) 

> 
> 
> fixed it with 
> ```
> sudo chown -R $USER:$GROUP ~/.npm
> sudo chown -R $USER:$GROUP ~/.config
> ```

**Comment by crrollyson** [comment] 2016-07-19 18:35
Same here, thanks!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by avastamin** [comment] 2016-07-20 13:25
Worked! thanks

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by anngelfra** [comment] 2016-07-22 15:14
Thank you, thank you. I had gone crazy trying to restart and uninstall and then I found these commands and IT WORKS <3

**Comment by ayibfanani** [comment] 2016-07-30 05:33
`sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config`

work like charm, thanks

**Comment by AnnaUmi** [comment] 2016-07-30 10:12
thanks you! It works
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by itumoraes** [comment] 2016-08-01 21:09
Finally! It works! Thanks!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by monis01** [comment] 2016-08-02 10:25
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

worked for me too, Thanks!

**Comment by jimbojw** [comment] 2016-08-02 11:43
The root cause of this issue (and many like it) is https://github.com/npm/write-file-atomic/issues/11.

There is an outstanding patch which will fix this for everyone. We're all waiting for someone from npm to accept it: https://github.com/npm/write-file-atomic/pull/13

**Comment by akohli96** [comment] 2016-08-06 23:20
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Worked for me too!

**Comment by eduard-ungureanu** [comment] 2016-08-10 14:32
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Worked for me too, on OSX EL Capitan

Thank you so much!

**Comment by Paras-avantsoft** [comment] 2016-08-11 04:54
thanks.. Its working.. on OSX EL Capitan

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by w9ahmed** [comment] 2016-08-11 16:06
Worked for me! 

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Andraw-lin** [comment] 2016-08-12 07:55
Works for me too !!!!! Thanks !!!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Bernardoow** [comment] 2016-08-12 19:28
Works for me too !!!!! Thanks !!!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Sekhno** [comment] 2016-08-18 16:27
Works for me too !!!!! Thanks !!!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by vinayakkulkarni** [comment] 2016-08-20 06:40
`sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config`

Worked like a charm! Thanks a ton!

**Comment by IgorTsapyak** [comment] 2016-08-21 11:53
Works for me!

Thanks...

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Philyorkshire** [comment] 2016-08-22 14:58
Worked for me, I got into this issue running 

`sudo bower install`

by mistake, which messed it all up. But then running 

`sudo chown -R $USER:$GROUP ~/.npm`
`sudo chown -R $USER:$GROUP ~/.config`

fixed it all for me.

**Comment by SibuStephen** [comment] 2016-08-23 07:58
Thank you @alexlaw17  :) 

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Carlos-Augusto** [comment] 2016-08-23 23:16
It worked like magic

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by iCristian** [comment] 2016-08-25 11:23
Thanks
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Work for me in ionic Framework Great!!

**Comment by rahul-jat** [comment] 2016-08-29 06:59
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

this worked for me as well. :)

**Comment by baaronp7** [comment] 2016-08-31 18:52
@appssunset 
Good call...
This is the one I needed:
sudo chown -R $USER:$GROUP ~/.cache

**Comment by shellygraham** [comment] 2016-09-05 19:42
@alexlaw17 - Thanks man!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Worked liked magic.
