### ISSUE TITLE
bower init failing, Unable to perform highlight

### ISSUE THREAD

**Issue by xoorath** [bower/bower#2427] opened 2017-02-06 02:08 UTC
Hey, I'm unable to get bower init to run without crashing.  Here's my output:

```
{lamb} bower init
 =====================Started:
? main file index.js
? keywords
? authors xoorath <jared@xoorath.com>
? license ISC
? homepage https://github.com/xoorath/miniature-disco
? set currently installed components as dependencies? Yes
? add commonly ignored files to ignore list? Yes
? would you like to mark this package as private which prevents it from being accidentally published to the reg? would you like to mark this package as private which prevents it from being accidentally published to the registry? No
bower error         Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL

Stack trace:
Error: Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL
    at throwError (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1161:21)
    at scanStringLiteral (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:944:13)
    at Object.advance (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1077:20)
    at collectToken (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:3293:23)
    at lookahead (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1118:18)
    at parseAssignmentExpression (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1992:17)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:3609:38
    at parseObjectProperty (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1425:28)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:3609:38
    at parseObjectInitialiser (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1449:24)

Console trace:
Error
    at StandardRenderer.error (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 6.9.5
OS: Windows_NT 10.0.14393 x64
```

**Comment by xoorath** [comment] 2017-02-06 02:10
Here are my version strings:

```
bower -v
1.8.0

node -v
v6.9.5

npm -v
3.10.10

git --version
git version 1.9.4.msysgit.0
```

**Comment by thinkxl** [comment] 2017-03-01 01:19
this may be related to https://github.com/bower/bower/issues/2153 can you paste your `bower.json` and `package.json` please.

**Comment by xoorath** [comment] 2017-03-01 18:52
@thinkxl I'm sorry to say, but I can't be certain if this issue isn't happening anymore or if I changed something and fixed it.... It's only been 24 days but I can't seem to remember what has changed.

None the less, maybe you can see something helpful.
`package.json`
```
{
  "name": "miniature-disco",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon --watch backend/**.ts --exec ts-node backend/server.ts"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/xoorath/miniature-disco.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/xoorath/miniature-disco/issues"
  },
  "homepage": "https://github.com/xoorath/miniature-disco",
  "dependencies": {
    "bower": "^1.8.0",
    "express": "^4.14.1",
    "gulp": "^3.9.1",
    "node-sass-middleware": "^0.11.0",
    "pug": "^2.0.0-beta11"
  },
  "devDependencies": {
    "@types/express": "^4.0.35",
    "@types/node": "^7.0.5",
    "@types/node-sass-middleware": "0.0.29",
    "@types/pug": "^2.0.4"
  }
}
```

`bower.json`
```
{
  "name": "minature-disco",
  "version": "0.0.1",
  "dependencies": {
    "jquery": "^3.1.1",
    "bootstrap": "^3.3.7"
  },
  "private": true
}

```

**Comment by thinkxl** [comment] 2017-04-13 05:31
I can't reproduce and it looks like it's not an issue for you anymore, I'm closing it for now. Feel free to open a new issue if you keep having problems.

**Closed by thinkxl** 2017-04-13 05:31 UTC
Labels: requires feedback

**Comment by DmitryPacificAtion** [comment] 2017-08-01 20:36
I have the same problem
bower -v
1.8.0

node -v
v7.2.0

npm -v
4.0.2

OS: Windows_NT 6.3.9600 x64
git version 2.9.2.windows.1
