### ISSUE TITLE
Package installation error with bower-angular-resource

### ISSUE THREAD

**Issue by Itsdenty** [bower/bower#2501] opened 2018-03-03 07:38 UTC
**Output of `bower -v && npm -v && node -v`:**
bower version: 1.8.2
NPM version: 5.5.1
Node version: 8.8.1
```
(paste your output here)

```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.Include angular-resource: "1.5.0" in your bower.json dependencies array
2. save the file
3.run bower install

**Describe the results you received:**

ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-resource.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-resource.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Describe the results you expected:**
Expected the package to be installed since every other package on my dependency list actually installed.

**Additional information:**
I believe this might be an issue with bower enforcing tlsv1 and the repository rejecting it . Since I don not know how to configure bower connection settings I believe this might help.

**Comment by timmonfette1** [comment] 2018-03-15 00:51
Ran into this issue as well, and like you, I assume the issue is that Bower is enforcing TLSv1 and last month Github deprecated it's support for TLSv1 and TLSv1.1 https://githubengineering.com/crypto-deprecation-notice/ so it stopped being able to connect to Github.

Since Bower is also deprecated, I don't know if they'll update it to fix this. What I did was migrated my dependencies off of Bower and into Yarn. It's relatively simple with `bower-away`. That will handle some of this migration for you by flattening all of your Bower dependencies into a package.json file (make sure you preserve any other package.json you have in your project already just in case it overwrites it) that you can then include as dependencies in any other package.json file you're using in your project. It'll put them all in a directory called `@bower_components` inside of your node_modules directory when you install them. https://bower.io/blog/2017/how-to-migrate-away-from-bower/

After that, you can just use Yarn to install them like any other dependency in your project. If you're relying on the existence of a bower_components directory for something, then include the `postinstall` script that `bower_away` includes in it's generated package.json in your final package.json. That script should create a link to `@bower_components` in your node_modules, but it'll be at the same level of your project as package.json and it'll be called bower_components so you can still use it where needed (tested on Windows, haven't had a chance to test if it links properly on Mac or Unix based OSes).

Obviously a migration like this may not be ideal for some projects (although you should move off of Bower and onto Yarn anyway), but unless Bower updates to use TLSv1.2 this is the best solution I found for fixing it.

**Comment by piebe** [comment] 2018-03-16 16:31
Upgrading your installed git will probably solve the problem

**Comment by timmonfette1** [comment] 2018-03-16 17:13
Can confirm that updating Git didn't solve the problem on Windows/Linux.

Same errors when attempting to do a `bower install`.  Even if that did somehow fix the problem, migrating away from Bower is still the best course of action to take.

**Comment by chilio** [comment] 2018-03-22 16:29
I've experienced some strange behavior too, and I couldn't find any solution for this.
In my case bower install errored randomly almost each time with different package. 
All packages were on github, so why suddenly ?

> unable to resolve github.com

Obviously something was wrong with networking. 
Errors were on **dockerized Ubuntu 16.04 running on virtualized rancher**, so a number of possible points of failure were pretty big.
But fortunately the solution was extremely simple. 
I realized that this is a basic installation and does not even have basic networking tools.
So after installing **`apt install net-tools iputils-ping`** all errors disappeared forever.
Pretty unexpected for me, hope it helps ...

**Comment by sheerun** [comment] 2018-03-28 11:25
"Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-resource.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-resource.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version"

It means that executing external git command has failed, this has nothing to do with some potential issue in Bower. Most likely git or openssl is old or network is broken in some way (firewall etc.). I'm going to close this issue.

**Closed by sheerun** 2018-03-28 11:25 UTC
