### ISSUE TITLE
Allow https urls to be registered in standard registry

### ISSUE THREAD

**Issue by herby** [bower/bower#1841] opened 2015-07-01 12:55 UTC
Please. Thanks.

**Comment by sheerun** [comment] 2015-07-28 22:09
https urls caused few issues in the past (especially with proxy configuration), so Bower decided to unify github urls in registry. Sorry, but it won't be implemented in standard registry.

**Comment by herby** [comment] 2015-07-29 09:47
You mean git urls, not github urls, I presume. I do not understand the reason either, bower client has support for https, and registry only holds the url, it's always the client which accesses it. ???

**Comment by sheerun** [comment] 2015-07-29 13:56
It has support for https, but it was decided we keep `git://` urls in public registry, because they caused the least issues for users. Other urls (like `https://` or `ssh://`) failed for few reasons, including proxy settings.

Why do you want to registrer https url?

**Comment by herby** [comment] 2015-07-29 14:00
Because some git hostings do not have `git://` protocol (like gitlab), probably because it needs proprietary daemon to run on specific port, which may seem a little strange for them (I would feel the same, `https://` is generic and battle-tested, `git://` is something special).

**Comment by herby** [comment] 2015-07-29 14:03
It it still possible to change `https://` to `git://` and try it first (or as a failback) in the client, if there were real issues. OTOH, I would presume proxy problems especially for users behind firewalls, where git:// just doesn't work (nonstandard port); but I do not know what were the actual problems there, so just assuming.

**Comment by sheerun** [comment] 2015-07-29 14:08
I've joined bower after that decision has been made, but afaik it was supposed to be feature, not a bug

If you setup your private registry you can turn off this feature by setting `skipNormalization` to true in https://github.com/bower/registry/blob/master/config/default.js

By the way, it seems it's not a bower's issue, but registry's "issue".

**Comment by herby** [comment] 2015-07-29 15:07
Well, registry repo is about registry code itself; this issue is about "setup of official bower registry", so I wasn't sure where to post it; it seemed a bit more relevant here. I can repost to registry repo if you think it belongs there.

**Comment by herby** [comment] 2015-07-29 15:20
BTW I looked at skipNormalization and it seems to do something else (it is not adding git:// nor is doing any action if protocol is present). Afaict registry accepts https url by default, the restriction is in fact in client itself (https://github.com/bower/bower/blob/833f97198ecf2b8e44549e8c3c8a0318dd09856f/lib/commands/register.js#L40).

**Comment by sheerun** [comment] 2015-07-29 15:27
Well, in that case we probably need to move this code to registry?

I'm no longer sure why Bower chose git:// over https:// . @satazor probably doesn't remember by now.

**Comment by herby** [comment] 2015-07-29 15:46
Other registries allow https and probably rely on it, so it would probably need some config guard as well (yes, it is logical for it to be there...), plus probably a specific error code for "registry only allows git://" in registry and its processing in the client... not a trivial move.

Anyway. The issue stays; it's of course your policy to only accept git://, but that means some repos just cannot be added. If it is not possible, it would be nice to know the reasons.

**Comment by davidjb** [comment] 2015-08-13 06:09
Sorry to intrude in the conversation, but just wanted to mention that ``https://`` is GitHub's recommended method of cloning for security (git:// is not secure) and compatibility (eg across firewalls): https://help.github.com/articles/which-remote-url-should-i-use/.  Concerns about performance have been negated by the introduction of smart HTTP for Git transport.

I asked GitHub several years ago why they stopped showing ``git://`` as a clone protocol for respositories and their response was the reasons above.  I've since asked them several times to highlight their internal "don't use git://' stance on their above documentation but it's never been followed through.

I'd be very interested in HTTPS URLs being available as the default transport protocol.  This may warrant another separate discussion, but from a security/eavesdropping standpoint, there's a good reason why GitHub's changed their default method.

**Comment by herby** [comment] 2016-05-02 13:54
How is the stance on this? Is it now possible / recommended for non-gh repos?

**Comment by sheerun** [comment] 2016-05-02 14:34
It is now possible and recommended (even forced). See #2235

**Closed by sheerun** 2016-05-02 14:34 UTC
Labels: discussion

**Comment by herby** [comment] 2016-05-02 16:10
I asked about non-Github ones. #2235 is about Github ones.

**Comment by sheerun** [comment] 2016-05-02 17:39
@herby Currently both client and server allow https urls

**Comment by herby** [comment] 2016-05-02 19:50
If that's the case, can I ask a little favour, as I would prefer to have https over git; could you change all entries with url `git://lolg.it/...` to use https instead? I cannot do it, as they are not able to unregister as they are non-github. Thanks.

P.S.: If possible, add final `.git` to helios, as I forgot to put it there when registering.

**Comment by sheerun** [comment] 2016-05-03 00:04
Could you open a ticket on bower/registry ?
