### ISSUE TITLE
[windows] [mingw] Register requires an interactive shell

### ISSUE THREAD

**Issue by akhiruddin** [bower/bower#2080] opened 2015-12-05 00:06 UTC
After  i remove the previous bower v1.6.8 and reinstall with latest version of bower v1.6.9
i tried to use init bower command, but it failed, and relay this message :

```
Samsung@Dean MINGW64 ~
$ bower init
bower ENOINT        Register requires an interactive shell

Additional error details:
Note that you can manually force an interactive shell with --config.interactive
```

can anyone help me?

@sheerun

**Comment by sheerun** [comment] 2015-12-05 12:14
It's duplicate of #1942. Fow now there's no known solution except using git bash instead of mingw.

**Closed by sheerun** 2015-12-05 12:14 UTC

**Comment by roseanngabon** [comment] 2015-12-15 11:56
I agree with sheerun. The solution is to install GIT bash and avoid using MinTTY and follow the documentation. 
Here is the solution:
1. Uninstall existing GIT bash
2. Reinstall GIT bash
3. Set up during installation:
3a: Select> <strong>Use Git form the Windows Command Prompt </strong>
3b: Select> <strong>Checkout Windows-style, commit Unix-style line endings</strong>
3c: Select> <strong>Use Windows' default console window</strong>

**Comment by cataquil** [comment] 2016-01-10 19:02
well you don't really have to uninstall/reinstall, you can just use the Win CMD. 
do you bower init then switch back to MinW64.
It would be great it it worked in MinTTY because that give you lots of nice unix
programs that are useful for node and js dev, getting code from git, and docker.  
Not to mention docker.

**Comment by cataquil** [comment] 2016-01-10 19:20
cmd.exe /C "C:\Program Files\Git\bin\bash.exe" --login -i

**Comment by adolfoaugusto** [comment] 2016-11-01 00:14
installing windows with bash git works good
follows the order, npm install -g bower, bower .... init and its dependencies.
