### ISSUE TITLE
ECMDERR - postuninstall hook throwing an error

### ISSUE THREAD

**Issue by shuhrat** [bower/bower#1594] opened 2014-11-11 14:34 UTC
I have a postinstall hook in my `.bowerrc`

``` javascript
"scripts": {
    "postinstall": "test -f postinstall.js && node postinstall.js"
}
```

getting an error after installing

```
ECMDERR Failed to execute "test -f postinstall.js [object Object] node postinstall.js", exit code of #2
```

**Comment by sheerun** [comment] 2015-01-05 00:09
I can confirm and reproduce. Please help to fix this by sending PR.

**Comment by zzarcon** [comment] 2015-11-26 20:43
@sheerun @albertinadx I gonna take a look into this as well

**Comment by albertinadx** [comment] 2015-11-26 20:45
Hi @zzarcon I had a fix for this, following how npm implements hooks. Would you like to review it as soon as I create the pull request?

**Comment by zzarcon** [comment] 2015-11-26 20:47
@albertinadx that's great, for sure! just let me know :)

**Comment by zzarcon** [comment] 2015-11-26 20:49
@albertinadx it's because of the script contains `&&`?

**Comment by albertinadx** [comment] 2015-11-26 21:34
It is because we are not allowing shell operators (for example &&) in the way we are executing the hooks scripts. I will finish this today. Thanks!

**Comment by sheerun** [comment] 2015-11-27 09:53
@albertinad Please send a test if possible :)

**Comment by zzarcon** [comment] 2015-11-27 11:48
@albertinadx good point, good job!

**Comment by sheerun** [comment] 2015-12-07 15:19
@albertinadx Any progress? :)

**Comment by albertinadx** [comment] 2015-12-15 19:51
@sheerun I'm back :), I will finish this in the following couple of days. I want to develop a couple of tests before making a PR.

**Comment by sheerun** [comment] 2016-03-05 20:44
@albertinadx Did you manage to finish the tests?

**Comment by BenMann** [comment] 2016-03-06 11:02
And with [that](https://github.com/bower/bower/pull/2197#issuecomment-192773428) we should be good to close! :tada:

**Comment by sheerun** [comment] 2016-04-04 16:51
I had to revert @albertinadx PR because /bin/sh is not available on Windows

**Comment by albertinadx** [comment] 2016-04-05 06:53
Thanks @sheerun, I will fix it tomorroe

**Comment by sheerun** [comment] 2016-04-05 10:27
Actually no need to fix it until we agree on appropriate solution.. Probably it would be better to wait for npm to implement similar feature.

**Comment by albertinad** [comment] 2016-04-05 14:44
Npm already has it, at least similar, and thus fix is based on that.

**Comment by albertinadx** [comment] 2016-04-05 14:45
Npm already has it, and this fix is based on that.

**Comment by sheerun** [comment] 2016-04-05 15:11
Really? I'll test your solution on Windows and merge if it works. Sorry, but I coudn't risk it for this patch release.

**Closed** 2020-04-27 18:00 UTC
Labels: bug
