### ISSUE TITLE
Error creating public directory when it already exists

### ISSUE THREAD

**Issue by jsloyer** [bower/bower#2189] opened 2016-02-26 15:45 UTC
Bower 1.7.7 is throwing an error when trying to create the public directory that already exists.

```
bower                           EACCES EACCES, mkdir '/public'

Stack trace:
Error: EACCES, mkdir '/public'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/Users/user/dev/app/node_modules/bower/lib/renderers/StandardRenderer.js:83:37)
    at Logger.<anonymous> (/Users/user/dev/app/node_modules/bower/lib/bin/bower.js:110:26)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/Users/user/dev/app/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/user/dev/app/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/Users/user/dev/app/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /Users/user/dev/app/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/Users/user/dev/app/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/user/dev/app/node_modules/bower/lib/node_modules/q/q.js:788:41)
    at /Users/user/dev/app/node_modules/bower/lib/node_modules/q/q.js:604:44
```

This should probably be changed to `mkdir -p` or check to see if the directory exists before force creating it...

**Comment by rajzshkr** [comment] 2016-02-29 13:39
can you comment the steps to reproduce this issue??

**Comment by jsloyer** [comment] 2016-02-29 13:44
Have a project that has a public dirctory created already, I used the following bower files for that.  Then run `bower install --config.interactive=false --allow-root`

**.bower.rc**
```
{
    "directory": "/public/assets/"
}
```

**bower.json**
```
{
  "name": "myapp",
  "version": "1.0.0",
  "private": false,
  "ignore": [
    "**/.*",
    "node_modules",
    "public/assets"
  ],
  "dependencies": {
    "bootstrap": "*",
    "jquery": "*",
    "html5shiv": "*",
    "respond": "*",
    "zeroclipboard": "*"
  }
}
```

**Comment by faceleg** [comment] 2016-02-29 17:05
Confirmed using steps provided (thanks @jsloyer!). Fails with just `bower install`.

**Comment by faceleg** [comment] 2016-02-29 17:06
Marked as beginner based on assumption that a simple `mkdir -p` modification is all that is required (+ tests!)

**Comment by jsloyer** [comment] 2016-03-01 00:33
@faceleg the issue is you can't do a `mkdir -p` with the Node library.  You will need to check for existence first then create directory if it exists.

**Comment by zacdoe** [comment] 2016-03-01 01:05
I would like to help out with this, but I am having some trouble reproducing the bug. It never complains about my pre-existing `/public` directory. I tried to find the guilty `mkdir` call and it appears to be in **bower/lib/core/Manager.js**

```
Manager.prototype.preinstall = function (json) {
    var that = this;
    var componentsDir = relativeToBaseDir(this._config.cwd)(this._config.directory);

    // If nothing to install, skip the code bellow
    if (mout.lang.isEmpty(that._dissected)) {
        return Q.resolve({});
    }

    return Q.nfcall(mkdirp, componentsDir)
    .then(function () {
        return scripts.preinstall(
            that._config, that._logger, that._dissected, that._installed, json
        );
    });
};
```

Assuming that `Q.nfcall(mkdirp, componentsDir)` is the offending mkdir call, it should be performing a `mkdir - p` using Q and the 'mkdirp' library. Any thoughts on this?

**Comment by jca258** [comment] 2016-03-03 02:28
Hi everyone, I've been testing this error on my machine and I think that is not an error. If you use:

**.bower.rc**
```
{
    "directory": "public/assets/"
}
```

It will work, as it should not throw any permission issue.
With `/public/assets/`, bower is trying to create the folder on the root of the file system.

**Comment by jsloyer** [comment] 2016-03-04 14:19
@jca258 you are right, that fixes the issue.

**Comment by faceleg** [comment] 2016-03-04 15:41
Closing as not a bug, as per @jca258's comment.

**Closed by faceleg** 2016-03-04 15:41 UTC
Labels: bug, help wanted, level:beginner
