### ISSUE TITLE
Getting "TypeError: set.filter is not a function" when attempting to register a package

### ISSUE THREAD

**Issue by autopulous** [bower/bower#2180] opened 2016-02-18 19:38 UTC
> C:\Users\jhart\Documents\Git\xsd>bower register xsd git://github.com/Paleoheurist/xsd.git
bower xsd#*                    resolve git://github.com/Paleoheurist/xsd.git#*
bower xsd#*                   download https://github.com/Paleoheurist/xsd/archive/1.0.0.tar.gz
bower xsd#*                    extract archive.tar.gz
bower xsd#*                      error set.filter is not a function

Stack trace:
TypeError: set.filter is not a function
    at IgnoreReader.addIgnoreRules (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\fstream-ignore\ignore
.js:148:13)
    at removeIgnores (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\util\removeIgnores.js:26:12)
    at GitHubResolver.Resolver._applyPkgMeta (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\Resolver.
js:206:12)
    at C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\Resolver.js:84:21
    at _fulfilled (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:796:13)
    at C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:604:44
    at runSingle (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:137:13)
    at flush (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:125:13)

Console trace:
Error
    at StandardRenderer.error (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
    at Logger.<anonymous> (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\jhart\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.7
Node version: 5.4.0
OS: Windows_NT 6.1.7601 x64

**Comment by Paleoheurist** [comment] 2016-02-18 22:15
I received the same error after I set up a dependency on the module in a project, as such:

  "dependencies" : {
    "xsd" : "git@github.com:Paleoheurist/xsd.git#1.0.0"
  }

I then proceeded to look into the error within my installation and placed the following test prior to `set.filter()` being called in `ignore.js`:

`if (null == set.filter) return;`

This test (for better or worse) got me past the issue... as to the side-effects of doing this or the cause of this I am unsure...

**Comment by Paleoheurist** [comment] 2016-02-19 04:58
I figured out how to fix my `bower.json` file - I needed to add the `ignore` property as follows:

`{"name": "xsd", "description": "XML Schema Definition", "version": "1.0.0",
"homepage": "http://www.vertexinc.com",
  "license": "MIT",
  "private": false,
  "main": "js/xsd.js",
  "ignore": ["test"],
  "dependencies": {},
  "moduleType": [
    "globals"
  ],
  "keywords": [
    "XSD",
    "XML",
    "Schema"
  ]
}`

It was my belief that the `ignore` property was optional...

**Comment by thinkxl** [comment] 2016-03-24 19:06
I think this is a support question and that you already figured it out, I'm going to go a head and close it for now.

**Closed by thinkxl** 2016-03-24 19:06 UTC
