### ISSUE TITLE
unexpected network errors during dependency installation (perhaps due to a network or server failure)

### ISSUE THREAD

**Issue by slavafomin** [bower/bower#2120] opened 2015-12-26 16:49 UTC
Hello there!

Thank you for your important work.

However, I'm experiencing network errors during dependency installation.

For example this is the final lines from the `bower install` output:

```
bower angular-sanitize#~1.4.7                                         retry Download of https://github.com/angular/bower-angular-sanitize/archive/v1.4.8.tar.gz failed with ETIMEDOUT, retrying in 1.3s
bower angular-sanitize#~1.4.7                                       extract archive.tar.gz
bower angular-sanitize#~1.4.7                                      resolved git://github.com/angular/bower-angular-sanitize.git#1.4.8
```

After those lines Bower is hanging indefinitely.

For some reason I have a lot of error messages like `ETIMEDOUT` and download retries. When I try to download the specified archives manually it works flawlessly through `wget` and Google Chrome. Each time the problem is with different package.

I have a very good stable ethernet connection. `npm` is working without any issues as well as all the other network-oriented software.

```
$ bower --version
1.7.1

$ node --version
v0.12.9

$ cat /etc/issue
Ubuntu 15.04 \n \l

$ uname -a
Linux destiny 3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

What could be the reason for this? How do I debug the situation?

Thank you!

**Comment by BenMann** [comment] 2015-12-27 08:47
This could(!) be related: to https://github.com/bower/bower/issues/2101. We're having issues with handling zip archives at the moment and it is not yet clear what the root cause is. Is upgrading your node version an option?

**Comment by slavafomin** [comment] 2015-12-27 13:04
I can't change Node version, because I have some packages that doesn't support newer version. 

However, I've tried to install dependencies using this bower.json on another machine with the same version of Node and it worked fine. It looks like I do have some strange network problems with GitHub, but it shouldn't make Bower to hang silently.

**Comment by carlosafonso** [comment] 2015-12-28 08:28
Hi,

FYI, I stumbled upon this as well. I was running 1.7.1 (OSX), but it keeps happening after downgrading to 1.7.0.

This occurs with a different package every time:
```
ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/FortAwesome/Font-Awesome.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.131]: errno=Operation timed out
```

I downgraded to 1.6.8 (the latest version in the 1.6.x series) and everything seems to be OK now.

**Comment by samccone** [comment] 2016-01-01 23:59
@azbshiri why did you close this?

**Comment by azbshiri** [comment] 2016-01-02 10:16
because this: 
> Update: it works fine now. Can't say what was causing this. Probably unstable network between me and GitHub. Probably we should test how stable Bower works in such situations somehow.

unexpected behaviors in an unstable network is a different situation and should have its own issue but I'd open the issue again and update its title to be more competitive

**Comment by sheerun** [comment] 2016-01-03 16:00
@azbshiri Please comment before closing / merging PRs and issues :)

**Comment by carlosafonso** [comment] 2016-01-04 09:48
Still running into this issue with v1.7.2. As @slavafomin said, I cannot tell whether it was GitHub's fault though. My network connection is very reliable however, and I haven't had this problem with any other software.

Retrying two or three times usually works.

**Comment by sheerun** [comment] 2020-04-27 19:59
If it still happens for someone, please open another issue

**Closed by sheerun** 2020-04-27 19:59 UTC
