### ISSUE TITLE
Register doesn't accept input from echo or redirect

### ISSUE THREAD

**Issue by andrew-boutin** [bower/bower#2431] opened 2017-02-13 16:15 UTC
The bower register command ignores input from both echo & redirect. Examples:

`echo -e 'USERNAME\nPASSWORD' | bower register package_name https://url.com/thing/repo.git`

&&

```
bower register package_name https://url.com/thing/repo.git << !
username
password
!
```

Both of these result in prompting the user for their GIT username & password as if they had only ran `bower register package_name https://url.com/thing/repo.git`. There is no error. The input is just ignored.

Is this a bug or the intended behavior? If it's intended then why is there no warning output at least to inform the user that the input will not be considered?

**Output of `bower -v && npm -v && node -v`:**

```
bower -v
1.8.0

npm -v
3.10.10

node -v
v7.2.1
```

**Additional environment details (proxy, private registry, etc.):**
Running in a Docker container based from `node:7.2.1-alpine`.

**Steps to reproduce the issue:**

1. Run `bower register package_name https://url.com/thing/repo.git`and observe being prompted for username + password.
2. Run the same command with attempting to echo in username + password instead `echo -e 'USERNAME\nPASSWORD' | bower register package_name https://url.com/thing/repo.git` to see how the input is ignored.
3. Run with input redirection to see how the input is still ignored
```
bower register package_name https://url.com/thing/repo.git << !
username
password
!
```

**Describe the results you received:**
The input from echo and redirection is completely ignored by bower register command. There is no error message or different output from regularly running the command. The username and password is prompted for like normal.

**Describe the results you expected:**
I expected the bower register command to accept my input for username and password so I wouldn't have to use the interactive prompt to complete the register command.

**Additional information:**
None.

**Comment by thinkxl** [comment] 2017-02-22 16:18
Hey @andrew-boutin, I think this is the intended behavior, a warning could be helpful, but not high priority right now. A pull requests are welcome :)

**Comment by andrew-boutin** [comment] 2017-02-22 17:30
@thinkxl if it's intended behavior could you please point me to where it's documented so I can read up on it? Thank you!

**Comment by thinkxl** [comment] 2017-02-22 18:02
Not documented, and my statement above is wrong. Is not intended behavior but functionality bower is missing, there are some benefits to accepting pipes, but not high priority right now.

Pull requests are welcome for functionality and documentation.

**Comment by andrew-boutin** [comment] 2017-02-24 13:53
OK thanks for your responses. I'll see if I can work on this sometime in the near future.

**Comment by thinkxl** [comment] 2017-07-21 03:41
Closing this as we won't be adding new features.

**Closed by thinkxl** 2017-07-21 03:41 UTC
Labels: enhancement, help wanted, low priority
